
import json

from ..Config import get_asset_path


def levenshtein_distance(s1, s2):
    if len(s1) < len(s2):
        return levenshtein_distance(s2, s1)

    if len(s2) == 0:
        return len(s1)

    previous_row = list(range(len(s2) + 1))
    for i, c1 in enumerate(s1):
        current_row = [i + 1]
        for j, c2 in enumerate(s2):
            insertions = previous_row[j + 1] + 1
            deletions = current_row[j] + 1
            substitutions = previous_row[j] + (c1 != c2)
            current_row.append(min(insertions, deletions, substitutions))
        previous_row = current_row

    return previous_row[-1]


suit_engineers = json.load(open(get_asset_path('suit_engineers.json')))
ship_engineers = json.load(open(get_asset_path('ship_engineers.json')))
engineering_modifications = json.load(open(get_asset_path('engineering_modifications.json')))

known_station_types = [
    "Asteroid base",
    "Coriolis Starport",
    "Mega ship",
    "Ocellus Starport",
    "Orbis Starport",
    "Outpost",
    "Planetary Outpost",
    "Planetary Port",
    "Settlement"
]

known_planet_types_obj = {
    "Planet": [
        "Ammonia world",
        "Class I gas giant",
        "Class II gas giant",
        "Class III gas giant",
        "Class IV gas giant",
        "Class V gas giant",
        "Earth-like world",
        "Gas giant with ammonia-based life",
        "Gas giant with water-based life",
        "Helium gas giant",
        "Helium-rich gas giant",
        "High metal content world",
        "Icy body",
        "Metal-rich body",
        "Rocky Ice world",
        "Rocky body",
        "Water giant",
        "Water world"
    ],
    "Star": [
        "A (Blue-White super giant) Star",
        "A (Blue-White) Star",
        "B (Blue-White super giant) Star",
        "B (Blue-White) Star",
        "Black Hole",
        "C Star",
        "CJ Star",
        "CN Star",
        "F (White super giant) Star",
        "F (White) Star",
        "G (White-Yellow super giant) Star",
        "G (White-Yellow) Star",
        "Herbig Ae/Be Star",
        "K (Yellow-Orange giant) Star",
        "K (Yellow-Orange) Star",
        "L (Brown dwarf) Star",
        "M (Red dwarf) Star",
        "M (Red giant) Star",
        "M (Red super giant) Star",
        "MS-type Star",
        "Neutron Star",
        "O (Blue-White) Star",
        "S-type Star",
        "Supermassive Black Hole",
        "T (Brown dwarf) Star",
        "T Tauri Star",
        "White Dwarf (D) Star",
        "White Dwarf (DA) Star",
        "White Dwarf (DAB) Star",
        "White Dwarf (DAV) Star",
        "White Dwarf (DAZ) Star",
        "White Dwarf (DB) Star",
        "White Dwarf (DBV) Star",
        "White Dwarf (DBZ) Star",
        "White Dwarf (DC) Star",
        "White Dwarf (DCV) Star",
        "White Dwarf (DQ) Star",
        "Wolf-Rayet C Star",
        "Wolf-Rayet N Star",
        "Wolf-Rayet NC Star",
        "Wolf-Rayet O Star",
        "Wolf-Rayet Star",
        "Y (Brown dwarf) Star"
    ]
}
known_planet_landmarks_obj = {
    "Abandoned Base": [
        "Abandoned Base"
    ],
    "Aleoida": [
        "Aleoida Arcus",
        "Aleoida Coronamus",
        "Aleoida Gravis",
        "Aleoida Laminiae",
        "Aleoida Spica"
    ],
    "Amphora Plant": [
        "Amphora Plant"
    ],
    "Anemone": [
        "Blatteum Bioluminescent Anemone",
        "Croceum Anemone",
        "Luteolum Anemone",
        "Prasinum Bioluminescent Anemone",
        "Puniceum Anemone",
        "Roseum Anemone",
        "Roseum Bioluminescent Anemone",
        "Rubeum Bioluminescent Anemone",
        "Unknown"
    ],
    "Aster": [
        "Cereum Aster Pod",
        "Cereum Aster Tree",
        "Lindigoticum Aster Pod",
        "Prasinum Aster Tree",
        "Rubellum Aster Tree"
    ],
    "Bacterium": [
        "Bacterium Acies",
        "Bacterium Alcyoneum",
        "Bacterium Aurasus",
        "Bacterium Bullaris",
        "Bacterium Cerbrus",
        "Bacterium Informem",
        "Bacterium Nebulus",
        "Bacterium Omentum",
        "Bacterium Scopulum",
        "Bacterium Tela",
        "Bacterium Verrata",
        "Bacterium Vesicula",
        "Bacterium Volu"
    ],
    "Bark Mounds": [
        "Bark Mounds"
    ],
    "Brain Tree": [
        "Aureum Brain Tree",
        "Gypseeum Brain Tree",
        "Lindigoticum Brain Tree",
        "Lividum Brain Tree",
        "Ostrinum Brain Tree",
        "Puniceum Brain Tree",
        "Roseum Brain Tree",
        "Viride Brain Tree"
    ],
    "Cactoida": [
        "Cactoida Cortexum",
        "Cactoida Lapis",
        "Cactoida Peperatis",
        "Cactoida Pullulanta",
        "Cactoida Vermis"
    ],
    "Calcite Plates": [
        "Lindigoticum Calcite Plates",
        "Luteolum Calcite Plates",
        "Rutulum Calcite Plates",
        "Viride Calcite Plates"
    ],
    "Chalice Pod": [
        "Albidum Chalice Pod",
        "Caeruleum Chalice Pod",
        "Ostrinum Chalice Pod",
        "Rubellum Chalice Pod",
        "Viride Chalice Pod"
    ],
    "Clypeus": [
        "Clypeus Lacrimam",
        "Clypeus Margaritus",
        "Clypeus Speculumi"
    ],
    "Collared Pod": [
        "Blatteum Collared Pod",
        "Lividum Collared Pod",
        "Rubicundum Collared Pod"
    ],
    "Concha": [
        "Concha Aureolas",
        "Concha Biconcavis",
        "Concha Labiata",
        "Concha Renibus"
    ],
    "Coral Tree": [
        "Coral Tree"
    ],
    "Crashed Ship": [
        "Crashed Ship"
    ],
    "Crystalline Shard": [
        "Crystalline Shards"
    ],
    "E-Type Anomaly": [
        "E02-Type Anomaly",
        "E03-Type Anomaly",
        "E04-Type Anomaly"
    ],
    "Electricae": [
        "Electricae Pluma",
        "Electricae Radialem"
    ],
    "Fonticulua": [
        "Fonticulua Campestris",
        "Fonticulua Digitos",
        "Fonticulua Fluctus",
        "Fonticulua Lapida",
        "Fonticulua Segmentatus",
        "Fonticulua Upupam"
    ],
    "Frutexa": [
        "Frutexa Acus",
        "Frutexa Collum",
        "Frutexa Fera",
        "Frutexa Flabellum",
        "Frutexa Flammasis",
        "Frutexa Metallicum",
        "Frutexa Sponsae"
    ],
    "Fumarole": [
        "Ammonia Ice Fumarole",
        "Carbon Dioxide Fumarole",
        "Carbon Dioxide Ice Fumarole",
        "Methane Ice Fumarole",
        "Nitrogen Ice Fumarole",
        "Silicate Vapour Fumarole",
        "Silicate Vapour Ice Fumarole",
        "Sulphur Dioxide Fumarole",
        "Sulphur Dioxide Ice Fumarole",
        "Water Fumarole",
        "Water Ice Fumarole"
    ],
    "Fumerola": [
        "Fumerola Aquatis",
        "Fumerola Carbosis",
        "Fumerola Extremus",
        "Fumerola Nitris"
    ],
    "Fungoida": [
        "Fungoida Bullarum",
        "Fungoida Gelata",
        "Fungoida Setisis",
        "Fungoida Stabitis"
    ],
    "Gas Vent": [
        "Carbon Dioxide Gas Vent",
        "Silicate Vapour Gas Vent",
        "Sulphur Dioxide Gas Vent",
        "Water Gas Vent"
    ],
    "Geyser": [
        "Ammonia Ice Geyser",
        "Carbon Dioxide Ice Geyser",
        "Methane Ice Geyser",
        "Nitrogen Ice Geyser",
        "Water Geyser",
        "Water Ice Geyser"
    ],
    "Guardian": [
        "Guardian Beacon",
        "Guardian Codex",
        "Guardian Data Terminal",
        "Guardian Pylon",
        "Guardian Relic Tower",
        "Guardian Sentinel"
    ],
    "Guardian Ruin": [
        "Unknown"
    ],
    "Guardian Structure": [
        "Bear",
        "Bowl",
        "Crossroads",
        "Fistbump",
        "Hammerbot",
        "Lacrosse",
        "Robolobster",
        "Squid",
        "Turtle",
        "Unknown"
    ],
    "Gyre": [
        "Aurarium Gyre Pod",
        "Aurarium Gyre Tree",
        "Roseum Gyre Pod",
        "Viride Gyre Tree"
    ],
    "Ice Crystals": [
        "Albidum Ice Crystals",
        "Flavum Ice Crystals",
        "Lindigoticum Ice Crystals",
        "Prasinum Ice Crystals",
        "Purpureum Ice Crystals",
        "Roseum Ice Crystals",
        "Rubeum Ice Crystals"
    ],
    "K-Type Anomaly": [
        "K01-Type Anomaly",
        "K03-Type Anomaly",
        "K04-Type Anomaly",
        "K05-Type Anomaly",
        "K06-Type Anomaly",
        "K08-Type Anomaly",
        "K09-Type Anomaly",
        "K10-Type Anomaly",
        "K12-Type Anomaly",
        "K13-Type Anomaly"
    ],
    "L-Type Anomaly": [
        "L01-Type Anomaly",
        "L04-Type Anomaly",
        "L06-Type Anomaly",
        "L07-Type Anomaly",
        "L08-Type Anomaly",
        "L09-Type Anomaly"
    ],
    "Lagrange Cloud": [
        "Caeruleum Lagrange Cloud",
        "Croceum Lagrange Cloud",
        "Luteolum Lagrange Cloud",
        "Proto-Lagrange Cloud",
        "Roseum Lagrange Cloud",
        "Rubicundum Lagrange Cloud",
        "Viride Lagrange Cloud"
    ],
    "Lava Spout": [
        "Iron Magma Lava Spout",
        "Silicate Magma Lava Spout"
    ],
    "Metallic Crystals": [
        "Flavum Metallic Crystals",
        "Prasinum Metallic Crystals",
        "Purpureum Metallic Crystals",
        "Rubeum Metallic Crystals"
    ],
    "Mineral Spheres": [
        "Lattice Mineral Spheres",
        "Solid Mineral Spheres"
    ],
    "Mollusc": [
        "Albens Bell Mollusc",
        "Albulum Gourd Mollusc",
        "Blatteum Bell Mollusc",
        "Caeruleum Gourd Mollusc",
        "Caeruleum Torus Mollusc",
        "Cereum Bullet Mollusc",
        "Cobalteum Globe Mollusc",
        "Croceum Globe Mollusc",
        "Croceum Gourd Mollusc",
        "Flavum Bullet Mollusc",
        "Flavum Torus Mollusc",
        "Gypseeum Bell Mollusc",
        "Lindigoticum Bell Mollusc",
        "Lindigoticum Bulb Mollusc",
        "Lindigoticum Capsule Mollusc",
        "Lindigoticum Parasol Mollusc",
        "Lindigoticum Reel Mollusc",
        "Lindigoticum Umbrella Mollusc",
        "Lividum Bullet Mollusc",
        "Luteolum Bell Mollusc",
        "Luteolum Bulb Mollusc",
        "Luteolum Capsule Mollusc",
        "Luteolum Parasol Mollusc",
        "Luteolum Reel Mollusc",
        "Luteolum Umbrella Mollusc",
        "Niveum Globe Mollusc",
        "Ostrinum Globe Mollusc",
        "Phoeniceum Gourd Mollusc",
        "Prasinum Globe Mollusc",
        "Purpureum Gourd Mollusc",
        "Roseum Globe Mollusc",
        "Rubeum Bullet Mollusc",
        "Rufum Gourd Mollusc",
        "Rutulum Globe Mollusc",
        "Viride Bulb Mollusc",
        "Viride Bullet Mollusc",
        "Viride Capsule Mollusc",
        "Viride Parasol Mollusc",
        "Viride Reel Mollusc",
        "Viride Umbrella Mollusc"
    ],
    "Osseus": [
        "Osseus Cornibus",
        "Osseus Discus",
        "Osseus Fractus",
        "Osseus Pellebantus",
        "Osseus Pumice",
        "Osseus Spiralis"
    ],
    "P-Type Anomaly": [
        "P01-Type Anomaly",
        "P02-Type Anomaly",
        "P03-Type Anomaly",
        "P04-Type Anomaly",
        "P05-Type Anomaly",
        "P07-Type Anomaly",
        "P09-Type Anomaly",
        "P11-Type Anomaly",
        "P12-Type Anomaly",
        "P13-Type Anomaly",
        "P14-Type Anomaly",
        "P15-Type Anomaly"
    ],
    "Peduncle": [
        "Albidum Peduncle Tree",
        "Caeruleum Peduncle Pod",
        "Caeruleum Peduncle Tree",
        "Candidum Peduncle Pod",
        "Gypseeum Peduncle Pod",
        "Ostrinum Peduncle Tree",
        "Purpureum Peduncle Pod",
        "Rubellum Peduncle Tree",
        "Rufum Peduncle Pod",
        "Viride Peduncle Tree"
    ],
    "Planets": [
        "Green Class I Gas Giant",
        "Green Class II Gas Giant",
        "Green Class III Gas Giant",
        "Green Class IV Gas Giant",
        "Green Gas Giant with Ammonia Life",
        "Green Water Giant"
    ],
    "Q-Type Anomaly": [
        "Q01-Type Anomaly",
        "Q02-Type Anomaly",
        "Q06-Type Anomaly",
        "Q08-Type Anomaly",
        "Q09-Type Anomaly"
    ],
    "Quadripartite": [
        "Albidum Quadripartite Pod",
        "Blatteum Quadripartite Pod",
        "Caeruleum Quadripartite Pod",
        "Viride Quadripartite Pod"
    ],
    "Recepta": [
        "Recepta Conditivus",
        "Recepta Deltahedronix",
        "Recepta Umbrux"
    ],
    "Rhizome": [
        "Candidum Rhizome Pod",
        "Cobalteum Rhizome Pod",
        "Gypseeum Rhizome Pod",
        "Purpureum Rhizome Pod",
        "Rubeum Rhizome Pod"
    ],
    "Shards": [
        "Crystalline Shards"
    ],
    "Silicate Crystals": [
        "Albidum Silicate Crystals",
        "Flavum Silicate Crystals",
        "Lindigoticum Silicate Crystals",
        "Prasinum Silicate Crystals",
        "Purpureum Silicate Crystals",
        "Roseum Silicate Crystals",
        "Rubeum Silicate Crystals"
    ],
    "Stolon": [
        "Stolon Pod"
    ],
    "Storm Cloud": [
        "Croceum Lagrange Storm Cloud",
        "Luteolum Lagrange Storm Cloud",
        "Roseum Lagrange Storm Cloud",
        "Rubicundum Lagrange Storm Cloud",
        "Viride Lagrange Storm Cloud"
    ],
    "Stratum": [
        "Stratum Araneamus",
        "Stratum Cucumisis",
        "Stratum Excutitus",
        "Stratum Frigus",
        "Stratum Laminamus",
        "Stratum Limaxus",
        "Stratum Paleas",
        "Stratum Tectonicas"
    ],
    "Surface Station": [
        "Crater Outpost",
        "Crater Port",
        "Installation",
        "Settlement",
        "Surface Station"
    ],
    "T-Type Anomaly": [
        "T01-Type Anomaly",
        "T03-Type Anomaly",
        "T04-Type Anomaly"
    ],
    "Thargoid": [
        "Common Thargoid Barnacle",
        "Coral Root",
        "Large Thargoid Barnacle",
        "Major Thargoid Spire",
        "Minor Thargoid Spire",
        "Primary Thargoid Spire",
        "Thargoid Banshees",
        "Thargoid Barnacle Barbs",
        "Thargoid Caustic Generator",
        "Thargoid Device",
        "Thargoid Interceptor Shipwreck",
        "Thargoid Mega Barnacles",
        "Thargoid Pod",
        "Thargoid Scavengers",
        "Thargoid Scout Shipwreck",
        "Thargoid Spire",
        "Thargoid Spires",
        "Thargoid Uplink Device"
    ],
    "Thargoid Barnacle": [
        "Unknown"
    ],
    "Thargoid Structure": [
        "Thargoid Structure"
    ],
    "Toughened Spear Roots": [
        "Toughened Spear Roots"
    ],
    "Tourist Beacon": [
        "Tourist Beacon"
    ],
    "Tubers": [
        "Albidum Sinuous Tubers",
        "Blatteum Sinuous Tubers",
        "Caeruleum Sinuous Tubers",
        "Lindigoticum Sinuous Tubers",
        "Prasinum Sinuous Tubers",
        "Roseum Sinuous Tubers",
        "Roseus Sinuous Tubers",
        "Violaceum Sinuous Tubers",
        "Viride Sinuous Tubers"
    ],
    "Tubus": [
        "Tubus Cavas",
        "Tubus Compagibus",
        "Tubus Conifer",
        "Tubus Rosarium",
        "Tubus Sororibus"
    ],
    "Tussock": [
        "Tussock Albata",
        "Tussock Capillum",
        "Tussock Caputus",
        "Tussock Catena",
        "Tussock Cultro",
        "Tussock Divisa",
        "Tussock Ignis",
        "Tussock Pennata",
        "Tussock Pennatis",
        "Tussock Propagito",
        "Tussock Serrati",
        "Tussock Stigmasis",
        "Tussock Triticum",
        "Tussock Ventusa",
        "Tussock Virgam"
    ],
    "Void": [
        "Caeruleum Octahedral Pod",
        "Chryseum Void Heart"
    ],
    "Wrecked Ship": [
        "Wrecked Ship"
    ]
}

known_subtypes = [item for sublist in known_planet_types_obj.values() for item in sublist]
known_landmarks = [item for sublist in known_planet_landmarks_obj.values() for item in sublist]

known_mining_commodities = [
    "Alexandrite",
    "Bauxite", 
    "Benitoite",
    "Bertrandite",
    "Bromellite",
    "Cobalt",
    "Coltan",
    "Gallite",
    "Grandidierite",
    "Hydrogen Peroxide",
    "Indite",
    "Lepidolite",
    "Liquid oxygen",
    "Lithium Hydroxide",
    "Low Temperature Diamonds",
    "Methane Clathrate",
    "Methanol Monohydrate Crystals",
    "Monazite",
    "Musgravite",
    "Painite",
    "Platinum",
    "Praseodymium",
    "Rhodplumsite",
    "Rutile",
    "Samarium",
    "Serendibite",
    "Tritium",
    "Uraninite",
    "Void Opal",
    "Water"
]
known_modules = [
    "AX Missile Rack",
    "AX Multi-Cannon",
    "Abrasion Blaster",
    "Advanced Docking Computer",
    "Advanced Missile Rack",
    "Advanced Multi-Cannon",
    "Advanced Planetary Approach Suite",
    "Advanced Plasma Accelerator",
    "Auto Field-Maintenance Unit",
    "Beam Laser",
    "Bi-Weave Shield Generator",
    "Burst Laser",
    "Business Class Passenger Cabin",
    "Cannon",
    "Cargo Rack",
    "Large Cargo Rack",
    "Cargo Scanner",
    "Caustic Sink Launcher",
    "Chaff Launcher",
    "Collector Limpet Controller",
    "Corrosion Resistant Cargo Rack",
    "Cytoscrambler Burst Laser",
    "Decontamination Limpet Controller",
    "Detailed Surface Scanner",
    "Economy Class Passenger Cabin",
    "Electronic Countermeasure",
    "Enforcer Cannon",
    "Enhanced AX Missile Rack",
    "Enhanced AX Multi-Cannon",
    "Enhanced Performance Thrusters",
    "Enhanced Xeno Scanner",
    "Enzyme Missile Rack",
    "Experimental Weapon Stabiliser",
    "Fighter Hangar",
    "First Class Passenger Cabin",
    "Fragment Cannon",
    "Frame Shift Drive",
    "Frame Shift Drive (SCO)",
    "Frame Shift Drive Interdictor",
    "Frame Shift Wake Scanner",
    "Fuel Scoop",
    "Fuel Tank",
    "Fuel Transfer Limpet Controller",
    "Guardian FSD Booster",
    "Guardian Gauss Cannon",
    "Guardian Hull Reinforcement",
    "Guardian Hybrid Power Distributor",
    "Guardian Hybrid Power Plant",
    "Guardian Module Reinforcement",
    "Guardian Nanite Torpedo Pylon",
    "Guardian Plasma Charger",
    "Guardian Shard Cannon",
    "Guardian Shield Reinforcement",
    "Hatch Breaker Limpet Controller",
    "Heat Sink Launcher",
    "Hull Reinforcement Package",
    "Imperial Hammer Rail Gun",
    "Kill Warrant Scanner",
    "Life Support",
    "Lightweight Alloy",
    "Luxury Class Passenger Cabin",
    "Meta Alloy Hull Reinforcement",
    "Military Grade Composite",
    "Mine Launcher",
    "Mining Lance",
    "Mining Laser",
    "Mining Multi Limpet Controller",
    "Mirrored Surface Composite",
    "Missile Rack",
    "Module Reinforcement Package",
    "Multi-Cannon",
    "Operations Multi Limpet Controller",
    "Pacifier Frag-Cannon",
    "Pack-Hound Missile Rack",
    "Planetary Approach Suite",
    "Planetary Vehicle Hangar",
    "Plasma Accelerator",
    "Point Defence",
    "Power Distributor",
    "Power Plant",
    "Prismatic Shield Generator",
    "Prospector Limpet Controller",
    "Pulse Disruptor Laser",
    "Pulse Laser",
    "Pulse Wave Analyser",
    "Pulse Wave Xeno Scanner",
    "Rail Gun",
    "Reactive Surface Composite",
    "Recon Limpet Controller",
    "Refinery",
    "Reinforced Alloy",
    "Remote Release Flak Launcher",
    "Remote Release Flechette Launcher",
    "Repair Limpet Controller",
    "Rescue Multi Limpet Controller",
    "Research Limpet Controller",
    "Retributor Beam Laser",
    "Rocket Propelled FSD Disruptor",
    "Seeker Missile Rack",
    "Seismic Charge Launcher",
    "Sensors",
    "Shield Booster",
    "Shield Cell Bank",
    "Shield Generator",
    "Shock Cannon",
    "Shock Mine Launcher",
    "Shutdown Field Neutraliser",
    "Standard Docking Computer",
    "Sub-Surface Displacement Missile",
    "Sub-Surface Extraction Missile",
    "Supercruise Assist",
    "Thargoid Pulse Neutraliser",
    "Thrusters",
    "Torpedo Pylon",
    "Universal Multi Limpet Controller",
    "Xeno Multi Limpet Controller",
    "Xeno Scanner"
]
known_commodities = [
    "AI Relics",
    "Advanced Catalysers",
    "Advanced Medicines",
    "Aepyornis Egg",
    "Aganippe Rush",
    "Agri-Medicines",
    "Agronomic Treatment",
    "Alacarakmo Skin Art",
    "Albino Quechua Mammoth Meat",
    "Alexandrite",
    "Algae",
    "Altairian Skin",
    "Aluminium",
    "Alya Body Soap",
    "Ancient Artefact",
    "Ancient Key",
    "Anduliga Fire Works",
    "Animal Meat",
    "Animal Monitors",
    "Anomaly Particles",
    "Antimatter Containment Unit",
    "Antique Jewellery",
    "Antiquities",
    "Any Na Coffee",
    "Apa Vietii",
    "Aquaponic Systems",
    "Arouca Conventual Sweets",
    "Articulation Motors",
    "Assault Plans",
    "Atmospheric Processors",
    "Auto-Fabricators",
    "Az Cancri Formula 42",
    "Azure Milk",
    "Baked Greebles",
    "Baltah'sine Vacuum Krill",
    "Banki Amphibious Leather",
    "Basic Medicines",
    "Bast Snake Gin",
    "Battle Weapons",
    "Bauxite",
    "Beer",
    "Belalans Ray Leather",
    "Benitoite",
    "Bertrandite",
    "Beryllium",
    "Bioreducing Lichen",
    "Biowaste",
    "Bismuth",
    "Black Box",
    "Bone Fragments",
    "Bootleg Liquor",
    "Borasetani Pathogenetics",
    "Bromellite",
    "Buckyball Beer Mats",
    "Building Fabricators",
    "Burnham Bile Distillate",
    "CD-75 Kitten Brand Coffee",
    "CMM Composite",
    "Caustic Tissue Sample",
    "Centauri Mega Gin",
    "Ceramic Composites",
    "Ceremonial Heike Tea",
    "Ceti Rabbits",
    "Chameleon Cloth",
    "Chateau De Aegaeon",
    "Chemical Waste",
    "Cherbones Blood Crystals",
    "Chi Eridani Marine Paste",
    "Classified Experimental Equipment",
    "Clothing",
    "Cobalt",
    "Coffee",
    "Coltan",
    "Combat Stabilisers",
    "Commercial Samples",
    "Computer Components",
    "Conductive Fabrics",
    "Consumer Technology",
    "Copper",
    "Coquim Spongiform Victuals",
    "Coral Sap",
    "Crom Silver Fesh",
    "Crop Harvesters",
    "Cryolite",
    "Crystalline Spheres",
    "Cyst Specimen",
    "Damaged Escape Pod",
    "Damna Carapaces",
    "Data Core",
    "Delta Phoenicis Palms",
    "Deuringas Truffles",
    "Diplomatic Bag",
    "Diso Ma Corn",
    "Domestic Appliances",
    "Duradrives",
    "Earth Relics",
    "Eden Apples of Aerial",
    "Eleu Thermals",
    "Emergency Power Cells",
    "Encrypted Correspondence",
    "Encrypted Data Storage",
    "Energy Grid Assembly",
    "Eranin Pearl Whisky",
    "Eshu Umbrellas",
    "Esuseku Caviar",
    "Ethgreze Tea Buds",
    "Evacuation Shelter",
    "Exhaust Manifold",
    "Experimental Chemicals",
    "Explosives",
    "Fish",
    "Food Cartridges",
    "Fossil Remnants",
    "Fruit and Vegetables",
    "Fujin Tea",
    "Galactic Travel Guide",
    "Gallite",
    "Gallium",
    "Geawen Dance Dust",
    "Gene Bank",
    "Geological Equipment",
    "Geological Samples",
    "Gerasian Gueuze Beer",
    "Giant Irukama Snails",
    "Giant Verrix",
    "Gilya Signature Weapons",
    "Gold",
    "Goman Yaupon Coffee",
    "Goslarite",
    "Grain",
    "Grandidierite",
    "Guardian Casket",
    "Guardian Orb",
    "Guardian Relic",
    "Guardian Tablet",
    "Guardian Totem",
    "Guardian Urn",
    "Haematite",
    "H.E. Suits",
    "HIP 10175 Bush Meat",
    "HIP 118311 Swarm",
    "HIP Organophosphates",
    "HIP Proto-Squid",
    "HN Shock Mount",
    "HR 7221 Wheat",
    "Hafnium 178",
    "Haiden Black Brew",
    "Hardware Diagnostic Sensor",
    "Harma Silver Sea Rum",
    "Havasupai Dream Catcher",
    "Heatsink Interlink",
    "Helvetitj Pearls",
    "Holva Duelling Blades",
    "Honesty Pills",
    "Hostages",
    "Hydrogen Fuel",
    "Hydrogen Peroxide",
    "Imperial Slaves",
    "Impure Spire Mineral",
    "Indi Bourbon",
    "Indite",
    "Indium",
    "Insulating Membrane",
    "Ion Distributor",
    "Jadeite",
    "Jaques Quinentian Still",
    "Jaradharre Puzzle Box",
    "Jaroua Rice",
    "Jotun Mookah",
    "Kachirigin Filter Leeches",
    "Kamitra Cigars",
    "Kamorin Historic Weapons",
    "Karetii Couture",
    "Karsuki Locusts",
    "Kinago Violins",
    "Kongga Ale",
    "Koro Kung Pellets",
    "LTT Hyper Sweet",
    "Land Enrichment Systems",
    "Landmines",
    "Lanthanum",
    "Large Survey Data Cache",
    "Lavian Brandy",
    "Leather",
    "Leathery Eggs",
    "Leestian Evil Juice",
    "Lepidolite",
    "Liquid oxygen",
    "Liquor",
    "Lithium",
    "Lithium Hydroxide",
    "Live Hecate Sea Worms",
    "Low Temperature Diamonds",
    "Lucan Onionhead",
    "Lyrae Weed",
    "Magnetic Emitter Coil",
    "Marine Equipment",
    "Master Chefs",
    "Mechucos High Tea",
    "Medb Starlube",
    "Medical Diagnostic Equipment",
    "Meta-Alloys",
    "Methane Clathrate",
    "Methanol Monohydrate Crystals",
    "Micro Controllers",
    "Micro-weave Cooling Hoses",
    "Microbial Furnaces",
    "Military Grade Fabrics",
    "Military Intelligence",
    "Military Plans",
    "Mineral Extractors",
    "Mineral Oil",
    "Modular Terminals",
    "Moissanite",
    "Mokojing Beast Feast",
    "Mollusc Brain Tissue",
    "Mollusc Fluid",
    "Mollusc Membrane",
    "Mollusc Mycelium",
    "Mollusc Soft Tissue",
    "Mollusc Spores",
    "Momus Bog Spaniel",
    "Monazite",
    "Motrona Experience Jelly",
    "Mukusubii Chitin-os",
    "Mulachi Giant Fungus",
    "Muon Imager",
    "Musgravite",
    "Mysterious Idol",
    "Nanobreakers",
    "Nanomedicines",
    "Narcotics",
    "Natural Fabrics",
    "Neofabric Insulation",
    "Neritus Berries",
    "Nerve Agents",
    "Ngadandari Fire Opals",
    "Nguna Modern Antiques",
    "Njangari Saddles",
    "Non Euclidian Exotanks",
    "Non-Lethal Weapons",
    "Occupied Escape Pod",
    "Ochoeng Chillies",
    "Onionhead",
    "Onionhead Alpha Strain",
    "Onionhead Beta Strain",
    "Onionhead Gamma Strain",
    "Ophiuch Exino Artefacts",
    "Organ Sample",
    "Orrerian Vicious Brew",
    "Osmium",
    "Painite",
    "Palladium",
    "Pantaa Prayer Sticks",
    "Pavonis Ear Grubs",
    "Performance Enhancers",
    "Personal Effects",
    "Personal Gifts",
    "Personal Weapons",
    "Pesticides",
    "Platinum",
    "Platinum Alloy",
    "Pod Core Tissue",
    "Pod Dead Tissue",
    "Pod Mesoglea",
    "Pod Outer Tissue",
    "Pod Shell Tissue",
    "Pod Surface Tissue",
    "Pod Tissue",
    "Political Prisoners",
    "Polymers",
    "Power Converter",
    "Power Generators",
    "Power Transfer Bus",
    "Praseodymium",
    "Precious Gems",
    "Progenitor Cells",
    "Prohibited Research Materials",
    "Protective Membrane Scrap",
    "Prototype Tech",
    "Pyrophyllite",
    "Radiation Baffle",
    "Rajukru Multi-Stoves",
    "Rapa Bao Snake Skins",
    "Rare Artwork",
    "Reactive Armour",
    "Rebel Transmissions",
    "Reinforced Mounting Plate",
    "Resonating Separators",
    "Rhodplumsite",
    "Robotics",
    "Rockforth Fertiliser",
    "Rusani Old Smokey",
    "Rutile",
    "SAP 8 Core Container",
    "Samarium",
    "Sanuma Decorative Meat",
    "Saxon Wine",
    "Scientific Research",
    "Scientific Samples",
    "Scrap",
    "Semi-Refined Spire Mineral",
    "Semiconductors",
    "Serendibite",
    "Shan's Charis Orchid",
    "Silver",
    "Skimmer Components",
    "Slaves",
    "Small Survey Data Cache",
    "Soontill Relics",
    "Sothis Crystalline Gold",
    "Space Pioneer Relics",
    "Steel",
    "Structural Regulators",
    "Superconductors",
    "Surface Stabilisers",
    "Survival Equipment",
    "Synthetic Fabrics",
    "Synthetic Meat",
    "Synthetic Reagents",
    "Taaffeite",
    "Tactical Data",
    "Tanmark Tranquil Tea",
    "Tantalum",
    "Tarach Spice",
    "Tauri Chimes",
    "Tea",
    "Technical Blueprints",
    "Telemetry Suite",
    "Terra Mater Blood Bores",
    "Thallium",
    "Thargoid Basilisk Tissue Sample",
    "Thargoid Biological Matter",
    "Thargoid Cyclops Tissue Sample",
    "Thargoid Glaive Tissue Sample",
    "Thargoid Heart",
    "Thargoid Hydra Tissue Sample",
    "Thargoid Link",
    "Thargoid Medusa Tissue Sample",
    "Thargoid Orthrus Tissue Sample",
    "Thargoid Probe",
    "Thargoid Resin",
    "Thargoid Scout Tissue Sample",
    "Thargoid Scythe Tissue Sample",
    "Thargoid Sensor",
    "Thargoid Technology Samples",
    "The Hutton Mug",
    "The Waters of Shintara",
    "Thermal Cooling Units",
    "Thorium",
    "Thrutis Cream",
    "Tiegfries Synth Silk",
    "Time Capsule",
    "Tiolce Waste2Paste Units",
    "Titan Deep Tissue Sample",
    "Titan Drive Component",
    "Titan Maw Deep Tissue Sample",
    "Titan Maw Partial Tissue Sample",
    "Titan Maw Tissue Sample",
    "Titan Partial Tissue Sample",
    "Titan Tissue Sample",
    "Titanium",
    "Tobacco",
    "Toxandji Virocide",
    "Toxic Waste",
    "Trade Data",
    "Trinkets of Hidden Fortune",
    "Tritium",
    "Ultra-Compact Processor Prototypes",
    "Unclassified Relic",
    "Unoccupied Escape Pod",
    "Unstable Data Core",
    "Uraninite",
    "Uranium",
    "Uszaian Tree Grub",
    "Utgaroar Millennial Eggs",
    "Uzumoku Low-G Wings",
    "V Herculis Body Rub",
    "Vanayequi Ceratomorpha Fur",
    "Vega Slimweed",
    "Vidavantian Lace",
    "Void Extract Coffee",
    "Void Opal",
    "Volkhab Bee Drones",
    "Water",
    "Water Purifiers",
    "Wheemete Wheat Cakes",
    "Wine",
    "Witchhaul Kobe Beef",
    "Wolf Fesh",
    "Wreckage Components",
    "Wulpa Hyperbore Systems",
    "Wuthielo Ku Froth",
    "Xenobiological Prison Pod",
    "Xihe Biomorphic Companions",
    "Yaso Kondi Leaf",
    "Zeessze Ant Grub Glue"
]
known_ships = [
    "Adder",
    "Alliance Challenger",
    "Alliance Chieftain",
    "Alliance Crusader",
    "Anaconda",
    "Asp Explorer",
    "Asp Scout",
    "Beluga Liner",
    "Cobra MkIII",
    "Cobra MkIV",
    "Corsair",
    "Diamondback Explorer",
    "Diamondback Scout",
    "Dolphin",
    "Eagle",
    "Federal Assault Ship",
    "Federal Corvette",
    "Federal Dropship",
    "Federal Gunship",
    "Fer-de-Lance",
    "Hauler",
    "Imperial Clipper",
    "Imperial Courier",
    "Imperial Cutter",
    "Imperial Eagle",
    "Keelback",
    "Krait MkII",
    "Krait Phantom",
    "Mamba",
    "Orca",
    "Panther Clipper",
    "Python",
    "Python MkII",
    "Sidewinder",
    "Type-10 Defender",
    "Type-6 Transporter",
    "Type-7 Transporter",
    "Type-8 Transporter",
    "Type-9 Heavy",
    "Viper MkIII",
    "Viper MkIV",
    "Vulture"
]
known_services = [
    "Apex Interstellar",
    "Bartender",
    "Black Market",
    "Colonisation Services",
    "Crew Lounge",
    "Fleet Carrier Administration",
    "Fleet Carrier Fuel",
    "Fleet Carrier Management",
    "Fleet Carrier Vendor",
    "Frontline Solutions",
    "Interstellar Factors Contact",
    "Market",
    "Material Trader",
    "Missions",
    "Outfitting",
    "Pioneer Supplies",
    "Powerplay",
    "Redemption Office",
    "Refinery Contact",
    "Refuel",
    "Repair",
    "Restock",
    "Search and Rescue",
    "Shipyard",
    "Shop",
    "Social Space",
    "System Colonisation"
    "Technology Broker",
    "Universal Cartographics",
    "Vista Genomics"
]

# Ship engineering materials (from Materials projection)
ship_raw_materials_map = {
    1: {1: ['carbon'], 2: ['vanadium'], 3: ['niobium'], 4: ['yttrium'], 'source': 'Yttrium Crystal Shards: Outotz LS-K D8-3, planet B 5 A and Brain Trees: 35 G. Carinae 2 D - trade afterwards at material trader'},
    2: {1: ['phosphorus'], 2: ['chromium'], 3: ['molybdenum'], 4: ['technetium'], 'source': 'Technetium Crystal Shards: HIP 36601, planet C 5 A and Brain Trees: 35 G. Carinae 2 A, HR 3230 3 A A - trade afterwards at material trader'},
    3: {1: ['sulphur'], 2: ['manganese'], 3: ['cadmium'], 4: ['ruthenium'], 'source': 'Ruthenium Crystal Shards: HIP 36601, planet C 1 D and Outotz LS-K D8-3, planet B 7 B and Brain Trees: 35 G. Carinae 2 C - trade afterwards at material trader'},
    4: {1: ['iron'], 2: ['zinc'], 3: ['tin'], 4: ['selenium'], 'source': 'Selenium Brain Trees: Kappa-1 Volantis, B 3 F A and HR 3230, 3 A A - trade afterwards at material trader'},
    5: {1: ['nickel'], 2: ['germanium'], 3: ['tungsten'], 4: ['tellurium'], 'source': 'Tellurium Crystal Shards: HIP 36601, planet C 3 B and Brain Trees: Synuefe SE-V B49-4 B 3 A - trade afterwards at material trader'},
    6: {1: ['rhenium'], 2: ['arsenic'], 3: ['mercury'], 4: ['polonium'], 'source': 'Polonium Crystal Shards: HIP 36601, planet C 1 A and Brain Trees: Synuefe AA-P C22-7 5 C - trade afterwards at material trader'},
    7: {1: ['lead'], 2: ['zirconium'], 3: ['boron'], 4: ['antimony'], 'source': 'Antimony Crystal Shards: Outotz LS-K D8-3, planet B 5 C and Brain Trees: 35 G. Carinae 1 E - trade afterwards at material trader'}
}
ship_manufactured_materials_map = {
    'Chemical': {
        1: ['chemicalstorageunits'], 2: ['chemicalprocessors'], 3: ['chemicaldistillery'],
        4: ['chemicalmanipulators'], 5: ['pharmaceuticalisolators'],
        'source': 'High Grade Emissions (Outbreak system states with pop >1000000) - trade afterwards at material trader, Mission reward'
    },
    'Thermic': {
        1: ['temperedalloys'], 2: ['heatresistantceramics'], 3: ['precipitatedalloys'],
        4: ['thermicalloys'], 5: ['militarygradealloys'],
        'source': 'High Grade Emissions (War, Civil War or Civil Unrest system states with pop >1000000) - trade afterwards at material trader, Mission reward'
    },
    'Heat': {
        1: ['heatconductionwiring'], 2: ['heatdispersionplate'], 3: ['heatexchangers'],
        4: ['heatvanes'], 5: ['protoheatradiators'],
        'source': 'High Grade Emissions (Boom state systems with pop >1000000) - trade afterwards at material trader, Mission reward'
    },
    'Conductive': {
        1: ['basicconductors'], 2: ['conductivecomponents'], 3: ['conductiveceramics'],
        4: ['conductivepolymers'], 5: ['biotechconductors'],
        'source': 'Mission Reward'
    },
    'Mechanical Components': {
        1: ['mechanicalscrap'], 2: ['mechanicalequipment'], 3: ['mechanicalcomponents'],
        4: ['configurablecomponents'], 5: ['improvisedcomponents'],
        'source': 'High Grade Emissions in Independent (Civil Unrest systems system states with pop >1000000) - trade afterwards at material trader'
    },
    'Capacitors': {
        1: ['gridresistors'], 2: ['hybridcapacitors'], 3: ['electrochemicalarrays'],
        4: ['polymercapacitors'], 5: ['militarysupercapacitors'],
        'source': 'High Grade Emissions in Independent and Alliance (War and Civil War system states with pop >1000000) - trade afterwards at material trader, Mission reward'
    },
    'Shielding': {
        1: ['wornshieldemitters'], 2: ['shieldemitters'], 3: ['shieldingsensors'],
        4: ['compoundshielding'], 5: ['imperialshielding'],
        'source': 'High Grade Emissions in Imperial systems (None and Election system states with pop >1000000) - trade afterwards at material trader, Mission reward'
    },
    'Composite': {
        1: ['compactcomposites'], 2: ['filamentcomposites'], 3: ['highdensitycomposites'],
        4: ['proprietarycomposites'], 5: ['coredynamicscomposites'],
        'source': 'High Grade Emissions in Federation systems (with pop >1000000) - trade afterwards at material trader'
    },
    'Crystals': {
        1: ['crystalshards'], 2: ['flawedfocuscrystals'], 3: ['focuscrystals'],
        4: ['refinedfocuscrystals'], 5: ['exquisitefocuscrystals'],
        'source': 'Mission reward'
    },
    'Alloys': {
        1: ['salvagedalloys'], 2: ['galvanisingalloys'], 3: ['phasealloys'],
        4: ['protolightalloys'], 5: ['protoradiolicalloys'],
        'source': 'High Grade Emissions (Boom state systems with pop >1000000) - trade afterwards at material trader'
    },
    'Guardian Technology': {
        1: ['guardian_sentinel_wreckagecomponents', 'guardianwreckagecomponents'],
        2: ['guardian_powercell', 'guardianpowercell'],
        3: ['guardian_powerconduit', 'guardianpowerconduit'],
        4: ['guardian_sentinel_weaponparts', 'guardiansentinelweaponparts'],
        5: ['guardian_techcomponent', 'techcomponent'],
        'source': 'Guardian sites: Synuefe HT-F D12-29 C3 (Technology Components), Synuefe LQ-T B50-1 B2 (modules), Synuefe GV-T B50-4 B1 (weapons)'
    },
    'Thargoid Technology': {
        1: ['tg_wreckagecomponents', 'wreckagecomponents', 'tg_abrasion02', 'tgabrasion02'],
        2: ['tg_biomechanicalconduits', 'biomechanicalconduits', 'tg_abrasion03', 'tgabrasion03'],
        3: ['tg_weaponparts', 'weaponparts', 'unknowncarapace', 'tg_causticshard', 'tgcausticshard'],
        4: ['tg_propulsionelement', 'propulsionelement', 'unknownenergycell', 'unknowncorechip'],
        5: ['tg_causticgeneratorparts', 'causticgeneratorparts', 'tg_causticcrystal', 'tgcausticcrystal', 'unknowntechnologycomponents'],
        'source': 'Titan graveyards, Non-Human Signal Sources Threat 4-5, Sensor Fragments: Solati - planet Halla (36.9423, -100.2683)'
    }
}

jameson_desc = 'HIP 12099 Planet 1B(Jameson crash site) - trade afterwards at material trader'
ship_encoded_materials_map = {
    'Emission Data': {
        1: ['scrambledemissiondata'], 2: ['archivedemissiondata'], 3: ['emissiondata'],
        4: ['decodedemissiondata'], 5: ['compactemissionsdata'],
        'source': jameson_desc
    },
    'Wake Scans': {
        1: ['disruptedwakeechoes'], 2: ['fsdtelemetry'], 3: ['wakesolutions'],
        4: ['hyperspacetrajectories'], 5: ['dataminedwake'],
        'source': jameson_desc
    },
    'Shield Data': {
        1: ['shieldcyclerecordings'], 2: ['shieldsoakanalysis'], 3: ['shielddensityreports'],
        4: ['shieldpatternanalysis'], 5: ['shieldfrequencydata'],
        'source': jameson_desc
    },
    'Encryption Files': {
        1: ['encryptedfiles'], 2: ['encryptioncodes'], 3: ['symmetrickeys'],
        4: ['encryptionarchives'], 5: ['adaptiveencryptors'],
        'source': jameson_desc
    },
    'Data Archives': {
        1: ['bulkscandata'], 2: ['scanarchives'], 3: ['scandatabanks'],
        4: ['encodedscandata'], 5: ['classifiedscandata'],
        'source': jameson_desc
    },
    'Encoded Firmware': {
        1: ['legacyfirmware'], 2: ['consumerfirmware'], 3: ['industrialfirmware'],
        4: ['securityfirmware'], 5: ['embeddedfirmware'],
        'source': jameson_desc
    },
    'Guardian Data': {
        1: ['ancientbiologicaldata'],
        2: ['ancientculturaldata'],
        3: ['ancienthistoricaldata'],
        4: ['ancienttechnologicaldata'],
        5: ['guardian_vesselblueprint'],
        'source': 'Guardian obelisks: Synuefe XR-H D11-102, planet 1 B (4 obelisks together)'
    },
    'Thargoid Data': {
        1: ['tg_interdictiondata'],
        2: ['tg_shipflightdata'],
        3: ['tg_shipsystemsdata'],
        4: ['tg_shutdowndata'],
        5: ['unknownshipsignature'],
        'source': 'Scanning thargoid ships and wakes'
    }
}

# Suit engineering materials (from ShipLocker projection) - no grades
suit_items_materials = [
    'weaponschematic', 'chemicalprocesssample', 'insightdatabank', 'personaldocuments',
    'chemicalsample', 'biochemicalagent', 'geneticsample', 'gmeds', 'healthmonitor',
    'inertiacanister', 'insight', 'ionisedgas', 'personalcomputer', 'syntheticgenome',
    'geneticrepairmeds', 'buildingschematic', 'compactlibrary', 'deepmantlesample',
    'hush', 'infinity', 'insightentertainmentsuite', 'lazarus', 'microbialinhibitor',
    'nutritionalconcentrate', 'push', 'shipschematic', 'surveillanceequipment',
    'universaltranslator', 'vehicleschematic', 'pyrolyticcatalyst', 'inorganiccontaminant',
    'agriculturalprocesssample', 'refinementprocesssample', 'compressionliquefiedgas',
    'degradedpowerregulator', 'largecapacitypowerregulator', 'powermiscindust',
    'powermisccomputer', 'powerequipment'
]
suit_components_materials = [
    'aerogel', 'chemicalcatalyst', 'chemicalsuperbase', 'circuitboard', 'circuitswitch',
    'electricalfuse', 'electricalwiring', 'encryptedmemorychip', 'epoxyadhesive',
    'memorychip', 'metalcoil', 'microhydraulics', 'microsupercapacitor', 'microthrusters',
    'microtransformer', 'motor', 'opticalfibre', 'opticallens', 'scrambler',
    'titaniumplating', 'transmitter', 'tungstencarbide', 'viscoelasticpolymer', 'rdx',
    'electromagnet', 'oxygenicbacteria', 'epinephrine', 'phneutraliser', 'microelectrode',
    'ionbattery', 'weaponcomponent'
]
suit_data_materials = [
    'internalcorrespondence', 'biometricdata', 'nocdata', 'axcombatlogs', 'airqualityreports',
    'audiologs', 'ballisticsdata', 'biologicalweapondata', 'catmedia', 'chemicalexperimentdata',
    'chemicalformulae', 'chemicalinventory', 'chemicalpatents', 'cocktailrecipes',
    'combatantperformance', 'conflicthistory', 'digitaldesigns', 'dutyrota', 'espionagematerial',
    'evacuationprotocols', 'explorationjournals', 'extractionyielddata', 'factionassociates',
    'financialprojections', 'factionnews', 'geneticresearch', 'influenceprojections',
    'kompromat', 'maintenancelogs', 'manufacturinginstructions', 'medicalrecords',
    'medicaltrialrecords', 'meetingminutes', 'mininganalytics', 'networkaccesshistory',
    'operationalmanual', 'opinionpolls', 'patrolroutes', 'politicalaffiliations',
    'productionreports', 'productionschedule', 'propaganda', 'radioactivitydata',
    'reactoroutputreview', 'recyclinglogs', 'securityexpenses', 'seedgeneaology',
    'settlementassaultplans', 'settlementdefenceplans', 'shareholderinformation',
    'smearcampaignplans', 'spectralanalysisdata', 'stellaractivitylogs', 'surveilleancelogs',
    'tacticalplans', 'taxrecords', 'topographicalsurveys', 'vaccineresearch',
    'visitorregister', 'weaponinventory', 'weapontestdata', 'xenodefenceprotocols',
    'geologicaldata', 'factiondonatorlist', 'pharmaceuticalpatents', 'powerresearchdata',
    'powerpropagandadata', 'poweremployeedata', 'powerclassifieddata', 'powerpreparationspyware'
]

suit_consumables_materials = [
    'healthpack', 'energycell', 'amm_grenade_emp', 'amm_grenade_frag',
    'amm_grenade_shield', 'bypass'
]

# Display names from game data
display_names = {
    # Ship materials - Raw
    'carbon': 'Carbon', 'vanadium': 'Vanadium', 'niobium': 'Niobium', 'yttrium': 'Yttrium',
    'phosphorus': 'Phosphorus', 'chromium': 'Chromium', 'molybdenum': 'Molybdenum',
    'technetium': 'Technetium', 'sulphur': 'Sulphur', 'manganese': 'Manganese',
    'cadmium': 'Cadmium', 'ruthenium': 'Ruthenium', 'iron': 'Iron', 'zinc': 'Zinc',
    'tin': 'Tin', 'selenium': 'Selenium', 'nickel': 'Nickel', 'germanium': 'Germanium',
    'tungsten': 'Tungsten', 'tellurium': 'Tellurium', 'rhenium': 'Rhenium',
    'arsenic': 'Arsenic', 'mercury': 'Mercury', 'polonium': 'Polonium', 'lead': 'Lead',
    'zirconium': 'Zirconium', 'boron': 'Boron', 'antimony': 'Antimony',

    # Ship materials - Manufactured (key examples)
    'chemicalstorageunits': 'Chemical Storage Units', 'temperedalloys': 'Tempered Alloys',
    'heatconductionwiring': 'Heat Conduction Wiring', 'basicconductors': 'Basic Conductors',
    'mechanicalscrap': 'Mechanical Scrap', 'gridresistors': 'Grid Resistors',
    'wornshieldemitters': 'Worn Shield Emitters', 'compactcomposites': 'Compact Composites',
    'crystalshards': 'Crystal Shards', 'salvagedalloys': 'Salvaged Alloys',

    # Ship materials - Encoded (key examples)
    'scrambledemissiondata': 'Exceptional Scrambled Emission Data',
    'disruptedwakeechoes': 'Atypical Disrupted Wake Echoes',
    'shieldcyclerecordings': 'Distorted Shield Cycle Recordings',
    'encryptedfiles': 'Unusual Encrypted Files', 'bulkscandata': 'Anomalous Bulk Scan Data',
    'legacyfirmware': 'Specialised Legacy Firmware',

    # Suit materials - Items
    'weaponschematic': 'Weapon Schematic', 'chemicalprocesssample': 'Chemical Process Sample',
    'insightdatabank': 'Insight Data Bank', 'personaldocuments': 'Personal Documents',
    'chemicalsample': 'Chemical Sample', 'biochemicalagent': 'Biochemical Agent',
    'geneticsample': 'Biological Sample', 'gmeds': 'G-Meds', 'healthmonitor': 'Health Monitor',
    'inertiacanister': 'Inertia Canister', 'ionisedgas': 'Ionised Gas',
    'personalcomputer': 'Personal Computer', 'syntheticgenome': 'Synthetic Genome',
    'geneticrepairmeds': 'Genetic Repair Meds', 'buildingschematic': 'Building Schematic',
    'compactlibrary': 'Compact Library', 'deepmantlesample': 'Deep Mantle Sample',
    'insightentertainmentsuite': 'Insight Entertainment Suite',
    'microbialinhibitor': 'Microbial Inhibitor', 'nutritionalconcentrate': 'Nutritional Concentrate',
    'shipschematic': 'Ship Schematic', 'surveillanceequipment': 'Surveillance Equipment',
    'universaltranslator': 'Universal Translator', 'vehicleschematic': 'Vehicle Schematic',
    'pyrolyticcatalyst': 'Pyrolytic Catalyst', 'inorganiccontaminant': 'Inorganic Contaminant',
    'agriculturalprocesssample': 'Agricultural Process Sample',
    'refinementprocesssample': 'Refinement Process Sample',
    'compressionliquefiedgas': 'Compression-Liquefied Gas',
    'degradedpowerregulator': 'Degraded Power Regulator',
    'largecapacitypowerregulator': 'Power Regulator', 'powermiscindust': 'Industrial Machinery',
    'powermisccomputer': 'Data Storage Device', 'powerequipment': 'Personal Protective Equipment',

    # Suit materials - Components
    'chemicalcatalyst': 'Chemical Catalyst', 'chemicalsuperbase': 'Chemical Superbase',
    'circuitboard': 'Circuit Board', 'circuitswitch': 'Circuit Switch',
    'electricalfuse': 'Electrical Fuse', 'electricalwiring': 'Electrical Wiring',
    'encryptedmemorychip': 'Encrypted Memory Chip', 'epoxyadhesive': 'Epoxy Adhesive',
    'memorychip': 'Memory Chip', 'metalcoil': 'Metal Coil', 'microhydraulics': 'Micro Hydraulics',
    'microsupercapacitor': 'Micro Supercapacitor', 'microthrusters': 'Micro Thrusters',
    'microtransformer': 'Micro Transformer', 'opticalfibre': 'Optical Fibre',
    'opticallens': 'Optical Lens', 'titaniumplating': 'Titanium Plating',
    'tungstencarbide': 'Tungsten Carbide', 'viscoelasticpolymer': 'Viscoelastic Polymer',
    'oxygenicbacteria': 'Oxygenic Bacteria', 'phneutraliser': 'pH Neutraliser',
    'ionbattery': 'Ion Battery', 'weaponcomponent': 'Weapon Component',

    # Suit materials - Data
    'internalcorrespondence': 'Internal Correspondence', 'biometricdata': 'Biometric Data',
    'nocdata': 'NOC Data', 'axcombatlogs': 'AX Combat Logs', 'airqualityreports': 'Air Quality Reports',
    'audiologs': 'Audio Logs', 'ballisticsdata': 'Ballistics Data',
    'biologicalweapondata': 'Biological Weapon Data', 'catmedia': 'Cat Media',
    'chemicalexperimentdata': 'Chemical Experiment Data', 'chemicalformulae': 'Chemical Formulae',
    'chemicalinventory': 'Chemical Inventory', 'chemicalpatents': 'Chemical Patents',
    'cocktailrecipes': 'Cocktail Recipes', 'combatantperformance': 'Combatant Performance',
    'conflicthistory': 'Conflict History', 'digitaldesigns': 'Digital Designs',
    'dutyrota': 'Duty Rota', 'espionagematerial': 'Espionage Material',
    'evacuationprotocols': 'Evacuation Protocols', 'explorationjournals': 'Exploration Journals',
    'extractionyielddata': 'Extraction Yield Data', 'factionassociates': 'Faction Associates',
    'financialprojections': 'Financial Projections', 'factionnews': 'Faction News',
    'geneticresearch': 'Genetic Research', 'influenceprojections': 'Influence Projections',
    'maintenancelogs': 'Maintenance Logs', 'manufacturinginstructions': 'Manufacturing Instructions',
    'medicalrecords': 'Medical Records', 'medicaltrialrecords': 'Clinical Trial Records',
    'meetingminutes': 'Meeting Minutes', 'mininganalytics': 'Mining Analytics',
    'networkaccesshistory': 'Network Access History', 'operationalmanual': 'Operational Manual',
    'opinionpolls': 'Opinion Polls', 'patrolroutes': 'Patrol Routes',
    'politicalaffiliations': 'Political Affiliations', 'productionreports': 'Production Reports',
    'productionschedule': 'Production Schedule', 'radioactivitydata': 'Radioactivity Data',
    'reactoroutputreview': 'Reactor Output Review', 'recyclinglogs': 'Recycling Logs',
    'securityexpenses': 'Security Expenses', 'seedgeneaology': 'Seed Geneaology',
    'settlementassaultplans': 'Settlement Assault Plans',
    'settlementdefenceplans': 'Settlement Defence Plans',
    'shareholderinformation': 'Shareholder Information',
    'smearcampaignplans': 'Smear Campaign Plans', 'spectralanalysisdata': 'Spectral Analysis Data',
    'stellaractivitylogs': 'Stellar Activity Logs', 'surveilleancelogs': 'Surveillance Logs',
    'tacticalplans': 'Tactical Plans', 'taxrecords': 'Tax Records',
    'topographicalsurveys': 'Topographical Surveys', 'vaccineresearch': 'Vaccine Research',
    'visitorregister': 'Visitor Register', 'weaponinventory': 'Weapon Inventory',
    'weapontestdata': 'Weapon Test Data', 'xenodefenceprotocols': 'Xeno-Defence Protocols',
    'geologicaldata': 'Geological Data', 'factiondonatorlist': 'Faction Donator List',
    'pharmaceuticalpatents': 'Pharmaceutical Patents', 'powerresearchdata': 'Power Research Data',
    'powerpropagandadata': 'Power Political Data', 'poweremployeedata': 'Power Association Data',
    'powerclassifieddata': 'Power Classified Data', 'powerpreparationspyware': 'Power Injection Malware',

    # Suit materials - Consumables
    'healthpack': 'Medkit', 'energycell': 'Energy Cell', 'amm_grenade_emp': 'Shield Disruptor',
    'amm_grenade_frag': 'Frag Grenade', 'amm_grenade_shield': 'Shield Projector', 'bypass': 'E-Breach'
}
known_allegiances = [
    "Alliance", "Empire", "Federation", "Guardian",
    "Independent", "Pilots Federation", "Player Pilots", "Thargoid"
]
known_governments = [
    "Anarchy", "Communism", "Confederacy", "Cooperative", "Corporate",
    "Democracy", "Dictatorship", "Feudal", "None", "Patronage",
    "Prison", "Prison Colony", "Theocracy"
]
known_states = [
    "Blight", "Boom", "Bust", "Civil Liberty", "Civil Unrest", "Civil War",
    "Drought", "Election", "Expansion", "Famine", "Infrastructure Failure",
    "Investment", "Lockdown", "Natural Disaster", "None", "Outbreak",
    "Pirate Attack", "Public Holiday", "Retreat", "Terrorist Attack", "War"
]
known_powers = ["A. Lavigny-Duval", "Aisling Duval", "Archon Delaine", "Denton Patreus", "Edmund Mahon",
                "Felicia Winters", "Jerome Archer", "Li Yong-Rui", "Nakato Kaine", "Pranav Antal", "Yuri Grom",
                "Zemina Torval"]
known_economies = [
    "Agriculture", "Colony", "Extraction", "High Tech", "Industrial",
    "Military", "None", "Refinery", "Service", "Terraforming", "Tourism"
]
known_security_levels = ["Anarchy", "High", "Low", "Medium"]
known_thargoid_war_states = ["None", "Thargoid Controlled", "Thargoid Harvest", "Thargoid Probing",
                                "Thargoid Recovery", "Thargoid Stronghold"]