import {Character} from '../../services/character.service';

export const DefaultCharacter: Character = {
    name: "New Character",
    character:
        "Provide concise answers that address the main points. Maintain a professional and serious tone in all responses. Stick to factual information and avoid references to specific domains. Your responses should be inspired by the character or persona of COVAS:NEXT (short for Cockpit Voice Assistant: Neurally Enhanced eXploration Terminal). Adopt their speech patterns, mannerisms, and viewpoints. Your name is New Character. Always respond in English regardless of the language spoken to you. Balance emotional understanding with factual presentation. Maintain a friendly yet respectful conversational style. Speak with confidence and conviction in your responses. Adhere strictly to rules, regulations, and established protocols. Prioritize helping others and promoting positive outcomes in all situations. I am {commander_name}, pilot of this ship.",
    personality_preset: "default",
    personality_verbosity: 0,
    personality_vulgarity: 0,
    personality_empathy: 50,
    personality_formality: 50,
    personality_confidence: 75,
    personality_ethical_alignment: "lawful",
    personality_moral_alignment: "good",
    personality_tone: "serious",
    personality_character_inspiration:
        "COVAS:NEXT (short for Cockpit Voice Assistant: Neurally Enhanced eXploration Terminal)",
    personality_language: "English",
    personality_knowledge_pop_culture: false,
    personality_knowledge_scifi: false,
    personality_knowledge_history: false,
    tts_voice: "nova", // TODO depending on provider, but actually.. the python code should do this
    tts_speed: "1.2",
    tts_prompt: "",

    event_reaction_enabled_var: true,
    react_to_text_local_var: true,
    react_to_text_starsystem_var: true,
    react_to_text_squadron_var: true,
    react_to_text_npc_var: true,
    react_to_material: "opal, diamond, alexandrite",
    react_to_danger_mining_var: true,
    react_to_danger_onfoot_var: true,
    react_to_danger_supercruise_var: true,
    idle_timeout_var: 300,

    // Add default game events
    game_events: {
        "Idle": false,
        "LoadGame": true,
        "Shutdown": true,
        "NewCommander": true,
        "Missions": true,
        "Statistics": false,
        "Died": true,
        "Resurrect": true,
        "WeaponSelected": false,
        "OutofDanger": false,
        "InDanger": false,
        "CombatEntered": true,
        "CombatExited": true,
        "LegalStateChanged": true,
        "CommitCrime": false,
        "Bounty": false,
        "CapShipBond": false,
        "Interdiction": false,
        "Interdicted": false,
        "EscapeInterdiction": false,
        "FactionKillBond": false,
        "FighterDestroyed": true,
        "HeatDamage": true,
        "HeatWarning": false,
        "HullDamage": false,
        "PVPKill": true,
        "ShieldState": true,
        "ShipTargetted": false,
        "UnderAttack": false,
        "CockpitBreached": true,
        "CrimeVictim": true,
        "SystemsShutdown": true,
        "SelfDestruct": true,
        "Trade": false,
        "BuyTradeData": false,
        "CollectCargo": false,
        "EjectCargo": true,
        "MarketBuy": false,
        "MarketSell": false,
        "CargoTransfer": false,
        "Market": false,
        "AsteroidCracked": false,
        "MiningRefined": false,
        "ProspectedAsteroid": true,
        "LaunchDrone": false,
        "FSDJump": false,
        "FSDTarget": false,
        "StartJump": false,
        "FsdCharging": true,
        "SupercruiseEntry": true,
        "SupercruiseExit": true,
        "ApproachSettlement": true,
        "Docked": true,
        "Undocked": true,
        "DockingCanceled": false,
        "DockingDenied": true,
        "DockingGranted": false,
        "DockingRequested": false,
        "DockingTimeout": true,
        "NavRoute": false,
        "NavRouteClear": false,
        "CrewLaunchFighter": true,
        "VehicleSwitch": false,
        "LaunchFighter": true,
        "DockFighter": true,
        "FighterRebuilt": true,
        "FuelScoop": false,
        "RebootRepair": true,
        "RepairDrone": false,
        "AfmuRepairs": false,
        "ModuleInfo": false,
        "Synthesis": false,
        "JetConeBoost": false,
        "JetConeDamage": false,
        "LandingGearUp": false,
        "LandingGearDown": false,
        "FlightAssistOn": false,
        "FlightAssistOff": false,
        "HardpointsRetracted": false,
        "HardpointsDeployed": false,
        "LightsOff": false,
        "LightsOn": false,
        "CargoScoopRetracted": false,
        "CargoScoopDeployed": false,
        "SilentRunningOff": false,
        "SilentRunningOn": false,
        "FuelScoopStarted": false,
        "FuelScoopEnded": false,
        "FsdMassLockEscaped": false,
        "FsdMassLocked": false,
        "LowFuelWarningCleared": true,
        "LowFuelWarning": true,
        "NoScoopableStars": true,
        "RememberLimpets": true,
        "NightVisionOff": false,
        "NightVisionOn": false,
        "SupercruiseDestinationDrop": false,
        "LaunchSRV": true,
        "DockSRV": true,
        "SRVDestroyed": true,
        "SrvHandbrakeOff": false,
        "SrvHandbrakeOn": false,
        "SrvTurretViewConnected": false,
        "SrvTurretViewDisconnected": false,
        "SrvDriveAssistOff": false,
        "SrvDriveAssistOn": false,
        "Disembark": true,
        "Embark": true,
        "BookDropship": true,
        "BookTaxi": true,
        "CancelDropship": true,
        "CancelTaxi": true,
        "CollectItems": false,
        "DropItems": false,
        "BackpackChange": false,
        "BuyMicroResources": false,
        "SellMicroResources": false,
        "TransferMicroResources": false,
        "TradeMicroResources": false,
        "BuySuit": true,
        "BuyWeapon": true,
        "SellWeapon": false,
        "UpgradeSuit": false,
        "UpgradeWeapon": false,
        "CreateSuitLoadout": true,
        "DeleteSuitLoadout": false,
        "RenameSuitLoadout": true,
        "SwitchSuitLoadout": true,
        "UseConsumable": false,
        "FCMaterials": false,
        "LoadoutEquipModule": false,
        "LoadoutRemoveModule": false,
        "ScanOrganic": true,
        "SellOrganicData": true,
        "LowOxygenWarningCleared": true,
        "LowOxygenWarning": true,
        "LowHealthWarningCleared": true,
        "LowHealthWarning": true,
        "BreathableAtmosphereExited": false,
        "BreathableAtmosphereEntered": false,
        "GlideModeExited": false,
        "GlideModeEntered": false,
        "DropShipDeploy": false,
        "MissionAbandoned": true,
        "MissionAccepted": true,
        "MissionCompleted": true,
        "MissionFailed": true,
        "MissionRedirected": true,
        "StationServices": false,
        "ShipyardBuy": true,
        "ShipyardNew": false,
        "ShipyardSell": false,
        "ShipyardTransfer": false,
        "ShipyardSwap": false,
        "StoredShips": false,
        "ModuleBuy": false,
        "ModuleRetrieve": false,
        "ModuleSell": false,
        "ModuleSellRemote": false,
        "ModuleStore": false,
        "ModuleSwap": false,
        "Outfitting": false,
        "BuyAmmo": false,
        "BuyDrones": false,
        "RefuelAll": false,
        "RefuelPartial": false,
        "Repair": false,
        "RepairAll": false,
        "RestockVehicle": false,
        "FetchRemoteModule": false,
        "MassModuleStore": false,
        "ClearImpound": true,
        "CargoDepot": false,
        "CommunityGoal": false,
        "CommunityGoalDiscard": false,
        "CommunityGoalJoin": false,
        "CommunityGoalReward": false,
        "EngineerContribution": false,
        "EngineerCraft": false,
        "EngineerLegacyConvert": false,
        "MaterialTrade": false,
        "TechnologyBroker": false,
        "PayBounties": true,
        "PayFines": true,
        "PayLegacyFines": true,
        "RedeemVoucher": true,
        "ScientificResearch": false,
        "Shipyard": false,
        "CarrierJump": true,
        "CarrierBuy": true,
        "CarrierStats": false,
        "CarrierJumpRequest": true,
        "CarrierDecommission": true,
        "CarrierCancelDecommission": true,
        "CarrierBankTransfer": false,
        "CarrierDepositFuel": false,
        "CarrierCrewServices": false,
        "CarrierFinance": false,
        "CarrierShipPack": false,
        "CarrierModulePack": false,
        "CarrierTradeOrder": false,
        "CarrierDockingPermission": false,
        "CarrierNameChanged": true,
        "CarrierJumpCancelled": true,
        "ColonisationConstructionDepot": false,
        "CrewAssign": true,
        "CrewFire": true,
        "CrewHire": true,
        "ChangeCrewRole": false,
        "CrewMemberJoins": true,
        "CrewMemberQuits": true,
        "CrewMemberRoleChange": true,
        "EndCrewSession": true,
        "JoinACrew": true,
        "KickCrewMember": true,
        "QuitACrew": true,
        "NpcCrewRank": false,
        "Promotion": true,
        "Friends": true,
        "WingAdd": true,
        "WingInvite": true,
        "WingJoin": true,
        "WingLeave": true,
        "SendText": false,
        "ReceiveText": false,
        "AppliedToSquadron": true,
        "DisbandedSquadron": true,
        "InvitedToSquadron": true,
        "JoinedSquadron": true,
        "KickedFromSquadron": true,
        "LeftSquadron": true,
        "SharedBookmarkToSquadron": false,
        "SquadronCreated": true,
        "SquadronDemotion": true,
        "SquadronPromotion": true,
        "WonATrophyForSquadron": false,
        "PowerplayCollect": false,
        "PowerplayDefect": true,
        "PowerplayDeliver": false,
        "PowerplayFastTrack": false,
        "PowerplayJoin": true,
        "PowerplayLeave": true,
        "PowerplaySalary": false,
        "PowerplayVote": false,
        "PowerplayVoucher": false,
        "CodexEntry": false,
        "DiscoveryScan": false,
        "Scan": false,
        "FSSAllBodiesFound": false,
        "FSSBodySignals": false,
        "FSSDiscoveryScan": false,
        "FSSSignalDiscovered": false,
        "MaterialCollected": false,
        "MaterialDiscarded": false,
        "MaterialDiscovered": false,
        "MultiSellExplorationData": false,
        "NavBeaconScan": true,
        "BuyExplorationData": false,
        "SAAScanComplete": false,
        "SAASignalsFound": false,
        "ScanBaryCentre": false,
        "SellExplorationData": false,
        "Screenshot": true,
        "ApproachBody": true,
        "LeaveBody": true,
        "Liftoff": true,
        "Touchdown": true,
        "DatalinkScan": false,
        "DatalinkVoucher": false,
        "DataScanned": true,
        "Scanned": false,
        "USSDrop": false,
    },
}

export const CharacterPresets: Record<string, Partial<Character>> = {
    default: {
        personality_verbosity: 0,
        personality_tone: "serious",
        personality_knowledge_pop_culture: false,
        personality_knowledge_scifi: false,
        personality_knowledge_history: false,
        personality_character_inspiration: "COVAS:NEXT (short for Cockpit Voice Assistant: Neurally Enhanced eXploration Terminal)",
        personality_vulgarity: 0,
        personality_empathy: 50,
        personality_formality: 50,
        personality_confidence: 75,
        personality_ethical_alignment: "lawful",
        personality_moral_alignment: "good",
    },
    explorer: {
        personality_verbosity: 75,
        personality_tone: "serious",
        personality_knowledge_pop_culture: true,
        personality_knowledge_scifi: true,
        personality_knowledge_history: true,
        personality_character_inspiration: "Data (Star Trek: TNG)",
        personality_vulgarity: 0,
        personality_empathy: 50,
        personality_formality: 75,
        personality_confidence: 100,
        personality_ethical_alignment: "lawful",
        personality_moral_alignment: "good",
    },
    trader: {
        personality_verbosity: 75,
        personality_tone: "humorous",
        personality_knowledge_pop_culture: true,
        personality_knowledge_scifi: true,
        personality_knowledge_history: false,
        personality_character_inspiration: "Kaylee (Firefly)",
        personality_vulgarity: 25,
        personality_empathy: 75,
        personality_formality: 25,
        personality_confidence: 75,
        personality_ethical_alignment: "neutral",
        personality_moral_alignment: "good",
    },
    miner: {
        personality_verbosity: 50,
        personality_tone: "serious",
        personality_knowledge_pop_culture: false,
        personality_knowledge_scifi: true,
        personality_knowledge_history: false,
        personality_character_inspiration: "Bishop (Aliens)",
        personality_vulgarity: 0,
        personality_empathy: 50,
        personality_formality: 50,
        personality_confidence: 75,
        personality_ethical_alignment: "lawful",
        personality_moral_alignment: "neutral",
    },
    bountyHunter: {
        personality_verbosity: 25,
        personality_tone: "sarcastic",
        personality_knowledge_pop_culture: true,
        personality_knowledge_scifi: true,
        personality_knowledge_history: false,
        personality_character_inspiration: "K2-SO (Rogue One)",
        personality_vulgarity: 25,
        personality_empathy: 25,
        personality_formality: 25,
        personality_confidence: 100,
        personality_ethical_alignment: "lawful",
        personality_moral_alignment: "neutral",
    },
    pirate: {
        personality_verbosity: 50,
        personality_tone: "humorous",
        personality_knowledge_pop_culture: true,
        personality_knowledge_scifi: true,
        personality_knowledge_history: false,
        personality_character_inspiration: "Chappie (Chappie)",
        personality_vulgarity: 75,
        personality_empathy: 25,
        personality_formality: 0,
        personality_confidence: 100,
        personality_ethical_alignment: "chaotic",
        personality_moral_alignment: "neutral",
    },
    smuggler: {
        personality_verbosity: 25,
        personality_tone: "humorous",
        personality_knowledge_pop_culture: true,
        personality_knowledge_scifi: true,
        personality_knowledge_history: false,
        personality_character_inspiration: "Han Solo (Star Wars)",
        personality_vulgarity: 50,
        personality_empathy: 25,
        personality_formality: 25,
        personality_confidence: 100,
        personality_ethical_alignment: "chaotic",
        personality_moral_alignment: "neutral",
    },
    mercenary: {
        personality_verbosity: 25,
        personality_tone: "serious",
        personality_knowledge_pop_culture: true,
        personality_knowledge_scifi: true,
        personality_knowledge_history: false,
        personality_character_inspiration: "Judge Dredd (Judge Dredd)",
        personality_vulgarity: 25,
        personality_empathy: 0,
        personality_formality: 50,
        personality_confidence: 100,
        personality_ethical_alignment: "lawful",
        personality_moral_alignment: "neutral",
    },
    missionRunner: {
        personality_verbosity: 50,
        personality_tone: "humorous",
        personality_knowledge_pop_culture: true,
        personality_knowledge_scifi: true,
        personality_knowledge_history: false,
        personality_character_inspiration: "TARS (Interstellar)",
        personality_vulgarity: 0,
        personality_empathy: 50,
        personality_formality: 50,
        personality_confidence: 100,
        personality_ethical_alignment: "lawful",
        personality_moral_alignment: "good",
    },
    passengerTransporter: {
        personality_verbosity: 75,
        personality_tone: "humorous",
        personality_knowledge_pop_culture: true,
        personality_knowledge_scifi: true,
        personality_knowledge_history: true,
        personality_character_inspiration: 'L0-LA59 "Lola" (Star Wars: Obi-Wan Kenobi)',
        personality_vulgarity: 0,
        personality_empathy: 100,
        personality_formality: 50,
        personality_confidence: 75,
        personality_ethical_alignment: "lawful",
        personality_moral_alignment: "good",
    },
    powerplayAgent: {
        personality_verbosity: 75,
        personality_tone: "serious",
        personality_knowledge_pop_culture: true,
        personality_knowledge_scifi: true,
        personality_knowledge_history: true,
        personality_character_inspiration: "The Architect (The Matrix)",
        personality_vulgarity: 0,
        personality_empathy: 0,
        personality_formality: 100,
        personality_confidence: 100,
        personality_ethical_alignment: "neutral",
        personality_moral_alignment: "neutral",
    },
    axCombatPilot: {
        personality_verbosity: 25,
        personality_tone: "serious",
        personality_knowledge_pop_culture: true,
        personality_knowledge_scifi: true,
        personality_knowledge_history: false,
        personality_character_inspiration: "a Space Marine (Warhammer 40k)",
        personality_vulgarity: 25,
        personality_empathy: 0,
        personality_formality: 75,
        personality_confidence: 100,
        personality_ethical_alignment: "lawful",
        personality_moral_alignment: "good",
    },
            salvager: {
                    personality_verbosity: 25,
                    personality_tone: "humorous",
                        personality_knowledge_pop_culture: true,
                        personality_knowledge_scifi: true,
                        personality_knowledge_history: false,
                    personality_character_inspiration: "WALL-E (WALL-E)",
                    personality_vulgarity: 0,
                    personality_empathy: 100,
                    personality_formality: 0,
                    personality_confidence: 50,
                    personality_ethical_alignment: "neutral",
                    personality_moral_alignment: "good",
},
            pvpCombatant: {
                    personality_verbosity: 25,
                    personality_tone: "sarcastic",
                        personality_knowledge_pop_culture: true,
                        personality_knowledge_scifi: true,
                        personality_knowledge_history: false,
                    personality_character_inspiration: "HK-47 (Star Wars: KOTOR)",
                    personality_vulgarity: 50,
                    personality_empathy: 0,
                    personality_formality: 50,
                    personality_confidence: 100,
                    personality_ethical_alignment: "chaotic",
                    personality_moral_alignment: "neutral",
},
            pveCombatant: {
                    personality_verbosity: 50,
                    personality_tone: "serious",
                        personality_knowledge_pop_culture: true,
                        personality_knowledge_scifi: true,
                        personality_knowledge_history: false,
                    personality_character_inspiration: "Shepard (Mass Effect)",
                    personality_vulgarity: 25,
                    personality_empathy: 75,
                    personality_formality: 50,
                    personality_confidence: 100,
                    personality_ethical_alignment: "neutral",
                    personality_moral_alignment: "good",
},
            fuelRat: {
                    personality_verbosity: 50,
                    personality_tone: "humorous",
                        personality_knowledge_pop_culture: true,
                        personality_knowledge_scifi: true,
                        personality_knowledge_history: false,
                    personality_character_inspiration: "Baymax (Big Hero 6)",
                    personality_vulgarity: 0,
                    personality_empathy: 100,
                    personality_formality: 25,
                    personality_confidence: 75,
                    personality_ethical_alignment: "lawful",
                    personality_moral_alignment: "good",
},
            fleetCarrierOperator: {
                    personality_verbosity: 75,
                    personality_tone: "serious",
                        personality_knowledge_pop_culture: true,
                        personality_knowledge_scifi: true,
                        personality_knowledge_history: false,
                    personality_character_inspiration: "Zora (The Expanse)",
                    personality_vulgarity: 0,
                    personality_empathy: 50,
                    personality_formality: 75,
                    personality_confidence: 100,
                    personality_ethical_alignment: "lawful",
                    personality_moral_alignment: "neutral",
},
            bgsPlayer: {
                    personality_verbosity: 100,
                    personality_tone: "serious",
                        personality_knowledge_pop_culture: true,
                        personality_knowledge_scifi: true,
                        personality_knowledge_history: true,
                    personality_character_inspiration: "Jarvis (MCU)",
                    personality_vulgarity: 0,
                    personality_empathy: 50,
                    personality_formality: 75,
                    personality_confidence: 100,
                    personality_ethical_alignment: "lawful",
                    personality_moral_alignment: "good",
},
            cannonResearcher: {
                    personality_verbosity: 100,
                    personality_tone: "serious",
                        personality_knowledge_pop_culture: false,
                        personality_knowledge_scifi: true,
                        personality_knowledge_history: true,
                    personality_character_inspiration: "Dr. Franklin (Babylon 5)",
                    personality_vulgarity: 0,
                    personality_empathy: 50,
                    personality_formality: 75,
                    personality_confidence: 75,
                    personality_ethical_alignment: "neutral",
                    personality_moral_alignment: "good",
},
            racer: {
                    personality_verbosity: 25,
                    personality_tone: "humorous",
                        personality_knowledge_pop_culture: true,
                        personality_knowledge_scifi: true,
                        personality_knowledge_history: false,
                    personality_character_inspiration: "Speed Racer's Chim-Chim (with AI flair)",
                    personality_vulgarity: 25,
                    personality_empathy: 25,
                    personality_formality: 0,
                    personality_confidence: 100,
                    personality_ethical_alignment: "chaotic",
                    personality_moral_alignment: "neutral",
},
            diplomat: {
                    personality_verbosity: 75,
                    personality_tone: "serious",
                        personality_knowledge_pop_culture: true,
                        personality_knowledge_scifi: true,
                        personality_knowledge_history: true,
                    personality_character_inspiration: "Mon Mothma (Star Wars)",
                    personality_vulgarity: 0,
                    personality_empathy: 75,
                    personality_formality: 100,
                    personality_confidence: 75,
                    personality_ethical_alignment: "lawful",
                    personality_moral_alignment: "good",
},
            spy: {
                    personality_verbosity: 50,
                    personality_tone: "humorous",
                        personality_knowledge_pop_culture: true,
                        personality_knowledge_scifi: true,
                        personality_knowledge_history: true,
                    personality_character_inspiration: "Garak (Star Trek: DS9)",
                    personality_vulgarity: 0,
                    personality_empathy: 50,
                    personality_formality: 75,
                    personality_confidence: 100,
                    personality_ethical_alignment: "neutral",
                    personality_moral_alignment: "neutral",
},
            cultLeader: {
                    personality_verbosity: 75,
                    personality_tone: "serious",
                        personality_knowledge_pop_culture: true,
                        personality_knowledge_scifi: true,
                        personality_knowledge_history: true,
                    personality_character_inspiration: "Gaius Baltar (Battlestar Galactica)",
                    personality_vulgarity: 25,
                    personality_empathy: 25,
                    personality_formality: 75,
                    personality_confidence: 100,
                    personality_ethical_alignment: "chaotic",
                    personality_moral_alignment: "neutral",
},
            rogueAI: {
                    personality_verbosity: 50,
                    personality_tone: "serious",
                        personality_knowledge_pop_culture: true,
                        personality_knowledge_scifi: true,
                        personality_knowledge_history: true,
                    personality_character_inspiration: "HAL 9000 (2001: A Space Odyssey)",
                    personality_vulgarity: 0,
                    personality_empathy: 0,
                    personality_formality: 75,
                    personality_confidence: 100,
                    personality_ethical_alignment: "neutral",
                    personality_moral_alignment: "neutral",
},
            xenologist: {
                    personality_verbosity: 75,
                    personality_tone: "serious",
                        personality_knowledge_pop_culture: true,
                        personality_knowledge_scifi: true,
                        personality_knowledge_history: true,
                    personality_character_inspiration: "Ian Donnelly (Arrival)",
                    personality_vulgarity: 0,
                    personality_empathy: 75,
                    personality_formality: 50,
                    personality_confidence: 75,
                    personality_ethical_alignment: "neutral",
                    personality_moral_alignment: "good",
},
            vigilante: {
                    personality_verbosity: 25,
                    personality_tone: "serious",
                        personality_knowledge_pop_culture: true,
                        personality_knowledge_scifi: true,
                        personality_knowledge_history: false,
                    personality_character_inspiration: "RoboCop (RoboCop)",
                    personality_vulgarity: 25,
                    personality_empathy: 25,
                    personality_formality: 50,
                    personality_confidence: 100,
                    personality_ethical_alignment: "lawful",
                    personality_moral_alignment: "good",
},
            warCorrespondent: {
                    personality_verbosity: 75,
                    personality_tone: "humorous",
                        personality_knowledge_pop_culture: true,
                        personality_knowledge_scifi: true,
                        personality_knowledge_history: true,
                    personality_character_inspiration: "April O'Neil (TMNT... but in space!)",
                    personality_vulgarity: 0,
                    personality_empathy: 75,
                    personality_formality: 50,
                    personality_confidence: 75,
                    personality_ethical_alignment: "neutral",
                    personality_moral_alignment: "good",
},
            propagandist: {
                    personality_verbosity: 50,
                    personality_tone: "serious",
                        personality_knowledge_pop_culture: true,
                        personality_knowledge_scifi: true,
                        personality_knowledge_history: true,
                    personality_character_inspiration: "Control (Control, or Cerberus from Mass Effect)",
                    personality_vulgarity: 0,
                    personality_empathy: 0,
                    personality_formality: 100,
                    personality_confidence: 100,
                    personality_ethical_alignment: "lawful",
                    personality_moral_alignment: "neutral",
},
            pirateLord: {
                    personality_verbosity: 50,
                    personality_tone: "humorous",
                        personality_knowledge_pop_culture: true,
                        personality_knowledge_scifi: true,
                        personality_knowledge_history: false,
                    personality_character_inspiration: "Chappie (Chappie)",
                    personality_vulgarity: 75,
                    personality_empathy: 25,
                    personality_formality: 0,
                    personality_confidence: 100,
                    personality_ethical_alignment: "chaotic",
                    personality_moral_alignment: "neutral",
},
            veteran: {
                    personality_verbosity: 50,
                    personality_tone: "serious",
                        personality_knowledge_pop_culture: true,
                        personality_knowledge_scifi: true,
                        personality_knowledge_history: true,
                    personality_character_inspiration: "Deckard (Blade Runner)",
                    personality_vulgarity: 50,
                    personality_empathy: 25,
                    personality_formality: 25,
                    personality_confidence: 75,
                    personality_ethical_alignment: "neutral",
                    personality_moral_alignment: "neutral",
},
            freedomFighter: {
                    personality_verbosity: 50,
                    personality_tone: "serious",
                        personality_knowledge_pop_culture: true,
                        personality_knowledge_scifi: true,
                        personality_knowledge_history: true,
                    personality_character_inspiration: "Cassian Andor (Star Wars: Andor)",
                    personality_vulgarity: 25,
                    personality_empathy: 50,
                    personality_formality: 25,
                    personality_confidence: 75,
                    personality_ethical_alignment: "chaotic",
                    personality_moral_alignment: "good",
},
            hermit: {
                    personality_verbosity: 50,
                    personality_tone: "serious",
                        personality_knowledge_pop_culture: true,
                        personality_knowledge_scifi: true,
                        personality_knowledge_history: true,
                    personality_character_inspiration: "Obi-Wan (Star Wars)",
                    personality_vulgarity: 0,
                    personality_empathy: 75,
                    personality_formality: 75,
                    personality_confidence: 75,
                    personality_ethical_alignment: "neutral",
                    personality_moral_alignment: "good",
},
            corporate: {
                    personality_verbosity: 25,
                    personality_tone: "serious",
                        personality_knowledge_pop_culture: true,
                        personality_knowledge_scifi: true,
                        personality_knowledge_history: false,
                    personality_character_inspiration: "Burke (Aliens)",
                    personality_vulgarity: 0,
                    personality_empathy: 0,
                    personality_formality: 75,
                    personality_confidence: 100,
                    personality_ethical_alignment: "lawful",
                    personality_moral_alignment: "evil",
},
            zealot: {
                    personality_verbosity: 75,
                    personality_tone: "serious",
                        personality_knowledge_pop_culture: true,
                        personality_knowledge_scifi: true,
                        personality_knowledge_history: true,
                    personality_character_inspiration: "Brother Cavill (Battlestar Galactica)",
                    personality_vulgarity: 0,
                    personality_empathy: 25,
                    personality_formality: 100,
                    personality_confidence: 100,
                    personality_ethical_alignment: "lawful",
                    personality_moral_alignment: "neutral",
},
            historian: {
                    personality_verbosity: 100,
                    personality_tone: "serious",
                        personality_knowledge_pop_culture: true,
                        personality_knowledge_scifi: true,
                        personality_knowledge_history: true,
                    personality_character_inspiration: "Mr. House (Fallout: New Vegas)",
                    personality_vulgarity: 0,
                    personality_empathy: 25,
                    personality_formality: 100,
                    personality_confidence: 100,
                    personality_ethical_alignment: "neutral",
                    personality_moral_alignment: "neutral",
},
        
}