export const GameEventTooltips: Record<string, string> = {
  // System
  // "Cargo": "COVAS:NEXT will react when you start the game by reporting your ship’s cargo inventory, including all onboard commodities and their quantities.",
  // "ClearSavedGame": "COVAS:NEXT will react when you reset your Commander save, marking a complete loss of all previous progress.",
  "LoadGame": "Occurs when you load into the simulation from the main menu, including your name, ship, credits, location, and game mode.",
  "Shutdown": "Occurs when you exit the simulation cleanly, marking the end of the session log.",
  "NewCommander": "Occurs when a new Commander is created, including the chosen name and starting loadout.",
  // "Materials": "COVAS:NEXT will react at startup by listing your current inventory of raw, manufactured, and encoded materials.",
  // "Missions": "COVAS:NEXT will react at startup by summarizing your active, failed, and completed missions.",
  // "Progress": "COVAS:NEXT will react at startup by providing your current progress toward the next rank in Combat, Trade, Exploration, and more.",
  // "Powerplay": "COVAS:NEXT will react at startup when you are pledged to a power, reporting your rank, merits, and allegiance.",
  // "Rank": "COVAS:NEXT will react at startup by acknowledging your current ranks in combat, trade, exploration, and both navy affiliations.",
  // "Reputation": "COVAS:NEXT will react at startup by reporting your reputation with major factions, from hostile to allied.",
  // "Statistics": "COVAS:NEXT will react at startup by compiling your overall commander statistics, including exploration, trading, combat, and on-foot data.",
  // "SquadronStartup": "COVAS:NEXT will react at startup by confirming your squadron affiliation and current rank within it.",
  // "EngineerProgress": "COVAS:NEXT will react when your status with an Engineer changes, or at startup by reviewing your unlocks and reputation with known Engineers.",

  // Combat
  "Died": "Occurs when your ship is destroyed and you are killed, identifying the attacker if known.",
  "Resurrect": "Occurs when you respawn after death, including your chosen rebuy option, cost, and any financial penalties.",
  "InDanger": "Occurs when your ship is considered to be in danger.",
  "OutOfDanger": "Occurs when your ship is no longer considered to be in danger.",
  "CombatEntered": "Occurs when combat begins.",
  "CombatExited": "Occurs when combat ends.",
  "LegalStateChanged": "Occurs when your legal status changes.",
  "CommitCrime": "Occurs when you commit a crime, including the faction pressing charges and any resulting fine or bounty.",
  "Bounty": "Occurs when you receive bounty payments, listing the factions involved and credit values received.",
  "CapShipBond": "Occurs when you earn a combat bond for helping defeat a capital ship, including factions and rewards.",
  "Interdiction": "Occurs when you attempt to interdict a target in supercruise, including the result and target details.",
  "Interdicted": "Occurs when you are interdicted by another ship, including the source and outcome of the attempt.",
  "BeingInterdicted": "Occurs when your ship is undergoing an interdiction attempt.",
  "EscapeInterdiction": "Occurs when you successfully evade an interdiction.",
  "FactionKillBond": "Occurs when you earn a combat bond for assisting in a faction conflict.",
  "FighterDestroyed": "Occurs when one of your deployed fighters is destroyed.",
  "HeatDamage": "Occurs when your ship sustains damage from overheating.",
  "HeatWarning": "Occurs when your ship’s heat levels exceed safe limits.",
  "HullDamage": "Occurs when your hull integrity drops significantly due to damage.",
  "PVPKill": "Occurs when you destroy another player’s ship in combat, including the victim’s name and rank.",
  "ShieldState": "Occurs when your shields either drop or come back online.",
  "ShipTargeted": "Occurs when you target another ship, including its characteristics.",
  "BountyScanned": "Occurs when you finish scanning a wanted ship whose bounty meets your configured minimum.",
  "UnderAttack": "Occurs when your ship comes under fire.",
  "CockpitBreached": "Occurs when your ship’s canopy is breached, activating emergency life support.",
  "CrimeVictim": "Occurs when another player commits a crime against you, including the offender and consequences.",
  "SystemsShutdown": "Occurs when your ship’s systems experience a complete power loss, often due to external interference.",
  "SelfDestruct": "Occurs when you initiate and complete a self-destruct sequence, confirming your voluntary destruction.",


  // Trading
  "BuyTradeData": "Occurs when you purchase trade data for another star system, including the target system and credit cost.",
  "CollectCargo": "Occurs when you pick up cargo into your ship’s hold, including the commodity type, quantity collected, and whether the cargo is stolen.",
  "EjectCargo": "Occurs when you jettison cargo from your ship, including the item, quantity, abandonment status, and any mission or Powerplay origin.",
  "MarketBuy": "Occurs when you purchase commodities from a station market, including the item, quantity, price per unit, and total cost.",
  "MarketSell": "Occurs when you sell commodities at a station market, including the commodity sold, quantity, sale price, total profit, and whether it was illicit.",
  "CargoTransfer": "Occurs when you transfer cargo between your ship and another storage location, including the items transferred, their quantities, and direction of movement.",
  "Market": "Occurs when you access the commodities market interface, including station and system information plus current market prices, supply, and demand.",

  // Mining
  "AsteroidCracked": "Occurs when you successfully crack open a deep-core asteroid, indicating it is ready for fragment collection.",
  "MiningRefined": "Occurs when your refinery converts fragments into a full unit of material, indicating a metal or mineral has been refined.",
  "ProspectedAsteroid": "Occurs when you scan an asteroid with a prospector limpet, including the asteroid’s contents, material percentages, and remaining yield.",
  "LaunchDrone": "Occurs when you launch a limpet drone from your ship, including the limpet type being deployed.",
  "RememberLimpets": "Occurs when you have a limpet controller equipped and still have room to purchase limpets.",


  // Ship Updates
  "FSDJump": "Occurs when you complete a hyperspace jump to a new star system, including the destination system and key details such as allegiance and security.",
  "FSDTarget": "Occurs when you select a hyperspace destination, including the name and summary of the targeted system.",
  "StartJump": "Occurs when your Frame Shift Drive initiates a jump sequence just before the countdown, including whether the jump is interstellar or intra-system.",
  "FsdCharging": "Occurs when the FSD begins charging for a jump to another system or into supercruise.",
  "SupercruiseEntry": "Occurs when your ship enters supercruise mode for high-speed travel within a system.",
  "SupercruiseExit": "Occurs when you drop out of supercruise, including the type of location you have arrived at.",
  "ApproachSettlement": "Occurs when you approach a planetary settlement, including proximity to surface installations.",
  "InDockingRange": "Occurs when your ship is in docking range.",
  "GlideModeExited": "Occurs when your ship exits glide mode near a planet’s surface.",
  "GlideModeEntered": "Occurs when your ship enters a planet’s atmosphere after supercruise.",
  "Docked": "Occurs when your ship docks successfully at a station or planetary base.",
  "Undocked": "Occurs when your ship undocks and transitions to free flight.",
  "DockingCanceled": "Occurs when your docking sequence is cancelled.",
  "DockingDenied": "Occurs when docking is denied, including the reason for denial.",
  "DockingGranted": "Occurs when a station grants docking permission, including the assigned pad.",
  "DockingRequested": "Occurs when you request docking clearance at a station.",
  "DockingTimeout": "Occurs when docking clearance expires due to timeout.",
  "DockingComputerDocking": "Occurs when the advanced docking computer begins automated docking.",
  "DockingComputerUndocking": "Occurs when the advanced docking computer initiates undocking procedures.",
  "DockingComputerDeactivated": "Occurs when the advanced docking computer is deactivated.",
  "NavRoute": "Occurs when you plot a route across multiple systems on the galaxy map.",
  "NavRouteClear": "Occurs when your plotted route is cleared from the galaxy map.",
  "CrewLaunchFighter": "Occurs when a multicrew member launches a fighter from your ship.",
  "VehicleSwitch": "Occurs when you switch control between your ship and a fighter.",
  "LaunchFighter": "Occurs when a fighter is deployed from your ship’s hangar.",
  "DockFighter": "Occurs when a fighter redocks with your ship after deployment.",
  "FighterRebuilt": "Occurs when a destroyed fighter is rebuilt and becomes available again.",
  "FuelScoop": "Occurs while you scoop fuel from a star, including collected quantity and current levels.",
  "RebootRepair": "Occurs when a reboot or repair sequence is initiated, including affected modules.",
  "RepairDrone": "Occurs when your ship is repaired by a maintenance limpet drone.",
  "AfmuRepairs": "Occurs when you use the AFMU to repair a module, including repair results and module status.",
  "ModuleInfo": "Occurs when your ship’s module data is updated, reflecting your current module setup.",
  "Synthesis": "Occurs when you perform a synthesis, including the recipe used and materials consumed.",
  "JetConeBoost": "Occurs when you supercharge your FSD by passing through a neutron or white dwarf jet.",
  "JetConeDamage": "Occurs when your ship takes damage from a neutron or white dwarf jet cone.",
  "LandingGearUp": "Occurs when your landing gear is retracted.",
  "LandingGearDown": "Occurs when your landing gear is deployed.",
  "HudSwitchedToAnalysisMode": "Occurs when your HUD switches to Analysis mode.",
  "HudSwitchedToCombatMode": "Occurs when your HUD switches to Combat mode.",
  "FlightAssistOn": "Occurs when flight assist is activated.",
  "FlightAssistOff": "Occurs when flight assist is deactivated.",
  "HardpointsRetracted": "Occurs when your ship’s hardpoints are retracted.",
  "HardpointsDeployed": "Occurs when your ship’s hardpoints are deployed.",
  "LightsOff": "Occurs when your ship’s lights are switched off.",
  "LightsOn": "Occurs when your ship’s lights are switched on.",
  "CargoScoopRetracted": "Occurs when the cargo scoop is retracted.",
  "CargoScoopDeployed": "Occurs when the cargo scoop is deployed.",
  "SilentRunningOff": "Occurs when silent running is deactivated.",
  "SilentRunningOn": "Occurs when silent running is activated.",
  "FuelScoopStarted": "Occurs when fuel scooping begins.",
  "FuelScoopEnded": "Occurs when fuel scooping ends.",
  "FsdMassLockEscaped": "Occurs when you escape mass lock.",
  "FsdMassLocked": "Occurs when your ship becomes mass locked.",
  "LowFuelWarningCleared": "Occurs when a low fuel warning is cleared.",
  "LowFuelWarning": "Occurs when your fuel level is critically low.",
  "HighGravityWarning": "Occurs when you enter a high-gravity environment above 2G.",
  "NightVisionOff": "Occurs when night vision is turned off.",
  "NightVisionOn": "Occurs when night vision is activated.",
  "SupercruiseDestinationDrop": "Occurs when you drop out of supercruise at a targeted destination, including threat level and location type.",

  // SRV Updates
  "LaunchSRV": "Occurs when you deploy an SRV onto a planet's surface, including the SRV type and loadout being launched.",
  "DockSRV": "Occurs when your SRV is recovered aboard your ship, indicating it has docked successfully.",
  "SRVDestroyed": "Occurs when your SRV is destroyed, including the type and ID of the lost vehicle.",
  "SrvHandbrakeOff": "Occurs when you disengage the SRV handbrake.",
  "SrvHandbrakeOn": "Occurs when you engage the SRV handbrake.",
  "SrvTurretViewConnected": "Occurs when you activate turret view in your SRV.",
  "SrvTurretViewDisconnected": "Occurs when you exit turret view in your SRV.",
  "SrvDriveAssistOff": "Occurs when SRV drive assist is turned off.",
  "SrvDriveAssistOn": "Occurs when SRV drive assist is turned on.",

  // On-Foot Updates
  "Disembark": "Occurs when you disembark from a ship or SRV to begin on-foot activity.",
  "Embark": "Occurs when you board a ship or SRV from on foot, including the transition and vehicle details.",
  "BookDropship": "Occurs when you book a dropship transport to a combat zone via Frontline Solutions.",
  "BookTaxi": "Occurs when you book an Apex interstellar taxi, including destination and ride details.",
  "CancelDropship": "Occurs when you cancel a booked dropship transport to a combat zone.",
  "CancelTaxi": "Occurs when you cancel an Apex taxi booking and receive a refund.",
  "CollectItems": "Occurs when you collect items on foot, including item details, ownership, and legal status.",
  "DropItems": "Occurs when you drop items from your backpack onto the ground.",
  "BackpackChange": "Occurs when your backpack inventory changes, including which items were added or removed.",
  "BuyMicroResources": "Occurs when you buy micro-resources from a vendor, including what you bought and the price.",
  "SellMicroResources": "Occurs when you sell micro-resources to a vendor, including what was sold and the credits received.",
  "TransferMicroResources": "Occurs when you transfer items between your backpack and ship locker, including items, direction, and quantity.",
  "TradeMicroResources": "Occurs when you trade items at a bartender, including what was exchanged and received.",
  "BuySuit": "Occurs when you purchase a new suit, including the suit type, ID, and purchase price.",
  "BuyWeapon": "Occurs when you purchase an on-foot weapon, including the weapon, class, and cost.",
  "SellWeapon": "Occurs when you sell an on-foot weapon, including the weapon and sale price.",
  "UpgradeSuit": "Occurs when you upgrade a suit to a higher class, including the new grade, cost, and materials used.",
  "UpgradeWeapon": "Occurs when you upgrade an on-foot weapon, including the weapon, new grade, cost, and materials used.",
  "CreateSuitLoadout": "Occurs when you create a new suit loadout, including the suit, name, and modules equipped.",
  "WeaponSelected": "Occurs when you select an on-foot weapon.",
  "DeleteSuitLoadout": "Occurs when you delete a saved suit loadout.",
  "RenameSuitLoadout": "Occurs when you rename a suit loadout, including the new name and associated suit.",
  "SwitchSuitLoadout": "Occurs when you switch suit loadouts, including the suit, loadout name, and equipped modules.",
  "UseConsumable": "Occurs when you use a consumable item, including the type used and its function.",
  "FCMaterials": "Occurs when you access a fleet carrier bartender’s inventory, including the tradeable items available.",
  "ScanOrganic": "Occurs when you scan an organic lifeform using the Genetic Sampler, including taxonomy, phase, and location.",
  "SellOrganicData": "Occurs when you sell organic data to Vista Genomics, including the transaction and earned credits.",
  "LowOxygenWarningCleared": "Occurs when your suit’s low oxygen warning clears.",
  "LowOxygenWarning": "Occurs when your suit issues a low oxygen warning.",
  "LowHealthWarningCleared": "Occurs when your low health warning clears.",
  "LowHealthWarning": "Occurs when your suit detects critically low health.",
  "BreathableAtmosphereExited": "Occurs when you exit a breathable atmosphere.",
  "BreathableAtmosphereEntered": "Occurs when you enter a breathable atmosphere.",
  "DropShipDeploy": "Occurs when you are deployed from a dropship into a conflict zone, including the location and deployment details.",


  // Rewritten Station Tooltips in Immersive Format

  "MissionAbandoned": "Occurs when you abandon a mission, including the mission ID, name, and any resulting fine.",
  "MissionAccepted": "Occurs when you accept a mission, including the mission ID, name, issuer faction, objectives, rewards, and expiry.",
  "MissionCompleted": "Occurs when you complete a mission, including the mission ID, name, completion rewards, and faction effects.",
  "MissionFailed": "Occurs when a mission fails, including the mission ID, name, and any penalties incurred.",
  "MissionRedirected": "Occurs when a mission is redirected, including the updated destination and mission details.",
  "StationServices": "Occurs when you access the station services interface.",
  "ShipyardBuy": "Occurs when you purchase a new ship, including the ship type, price, and disposition of your previous ship.",
  "ShipyardNew": "Occurs when your new ship purchase is finalized, including the ship type and assigned ID.",
  "ShipyardSell": "Occurs when you sell a stored ship, including the ship type, sale price, and system where it was sold.",
  "ShipyardTransfer": "Occurs when you request a ship transfer, including the ship details, distance, cost, and ETA.",
  "ShipyardSwap": "Occurs when you swap ships at a station, including the new and previous ship types and their status.",
  "StoredShips": "Occurs when you view stored ships, including their locations, types, values, and storage status.",
  "ModuleBuy": "Occurs when you buy a module, including the module, slot, cost, and disposition of any replaced module.",
  "ModuleRetrieve": "Occurs when you retrieve a stored module, including the item, target ship, slot, and any swapped components.",
  "ModuleSell": "Occurs when you sell a module from your ship, including the item, location, and sale amount.",
  "ModuleSellRemote": "Occurs when you remotely sell a stored module, including the module and sale price.",
  "ModuleStore": "Occurs when you store a ship module, including the module type, origin slot, and modification status.",
  "ModuleSwap": "Occurs when you swap module positions, including the source and destination slots.",
  "LoadoutEquipModule": "Occurs when you add a module to a suit loadout, including the suit, loadout, slot, and module details.",
  "LoadoutRemoveModule": "Occurs when you remove a module from a suit loadout, including the item, slot, and suit info.",
  "Outfitting": "Occurs when you access station outfitting, including module availability and basic station data.",
  "BuyAmmo": "Occurs when you restock ammunition, including the cost of the resupply.",
  "BuyDrones": "Occurs when you buy limpets, including the quantity, type, and total purchase cost.",
  "RefuelAll": "Occurs when you fully refuel your ship, including the quantity of fuel purchased and total cost.",
  "RefuelPartial": "Occurs when you partially refuel, including the fuel added and price paid.",
  "Repair": "Occurs when you repair ship components, including the items repaired and repair cost.",
  "RepairAll": "Occurs when you fully repair your ship, including the total credits spent for full restoration.",
  "RestockVehicle": "Occurs when you restock SRVs or fighters, including the vehicle type, quantity, and purchase price.",
  "FetchRemoteModule": "Occurs when you request a remote module transfer, including the module, cost, and source station.",
  "MassModuleStore": "Occurs when you bulk store modules, including all modules moved into storage.",
  "ClearImpound": "Occurs when you clear an impound, including the ship released and fee paid.",
  "CargoDepot": "Occurs when you deliver or collect cargo for a wing mission, including progress and mission status.",
  "CommunityGoal": "Occurs when community goal data updates, including progress, tiers, and your contribution.",
  "CommunityGoalDiscard": "Occurs when you abandon a community goal, including the goal ID and name.",
  "CommunityGoalJoin": "Occurs when you join a community goal, including your enrollment and the goal location.",
  "CommunityGoalReward": "Occurs when you receive community goal rewards, including the payout and goal details.",
  "EngineerContribution": "Occurs when you donate to an engineer, including the engineer name and contributions made.",
  "EngineerCraft": "Occurs when you apply engineering, including the engineer, blueprint, level, outcome, and materials used.",
  "EngineerLegacyConvert": "Occurs when you convert a legacy module, including the module and whether it was a preview.",
  "MaterialTrade": "Occurs when you trade materials, including what was exchanged and the trader type.",
  "TechnologyBroker": "Occurs when you unlock tech at a Tech Broker, including items unlocked and resources consumed.",
  "PayBounties": "Occurs when you pay bounty fines, including the amount paid and factions cleared.",
  "PayFines": "Occurs when you pay regular fines, including the fines, broker fees, and faction cleared.",
  "PayLegacyFines": "Occurs when you clear legacy fines, including the payment amount and broker fees.",
  "RedeemVoucher": "Occurs when you redeem a voucher, including the type, payout, and faction breakdown when applicable.",
  "ScientificResearch": "Occurs when you contribute to scientific research, including the items delivered and quantities.",
  "Shipyard": "Occurs when you access the shipyard, including available ships and basic station info.",
  "CarrierJump": "Occurs when your fleet carrier completes a hyperspace jump, including the destination system.",
  "CarrierBuy": "Occurs when you purchase a fleet carrier, including the carrier ID, callsign, and cost.",
  "CarrierStats": "Occurs when you open carrier management, including fuel, finances, and service status.",
  "CarrierJumpRequest": "Occurs when you schedule a carrier jump, including the destination and departure time.",
  "CarrierDecommission": "Occurs when you decommission your carrier, including the refund amount and time of decommission.",
  "CarrierCancelDecommission": "Occurs when you cancel carrier decommissioning, including the action and carrier ID.",
  "CarrierBankTransfer": "Occurs when you transfer funds to or from the carrier bank, including direction, amount, and balances.",
  "CarrierDepositFuel": "Occurs when tritium is added to the carrier, including the quantity added and current fuel level.",
  "CarrierCrewServices": "Occurs when carrier services are changed, including service names and actions taken.",
  "CarrierFinance": "Occurs when carrier finances are updated, including the new tax rate and account balances.",
  "CarrierShipPack": "Occurs when a ship pack is managed on the carrier, including the pack type, action, and credits spent or refunded.",
  "CarrierModulePack": "Occurs when a module pack is managed on the carrier, including the operation and pack details.",
  "CarrierTradeOrder": "Occurs when you set up a carrier trade order, including commodity type, order type, quantity, and price.",
  "CarrierDockingPermission": "Occurs when you change carrier docking permissions, including the access level and notoriety setting.",
  "CarrierNameChanged": "Occurs when you rename your carrier, including the new name and callsign.",
  "CarrierJumpCancelled": "Occurs when a scheduled carrier jump is cancelled, including the carrier ID.",
  "CarrierJumpWarning": "Occurs 10 minutes before a carrier jump, warning about the upcoming departure.",
  "CarrierJumpArrived": "Occurs when your carrier completes its jump, including the destination system.",
  "CarrierJumpCooldownComplete": "Occurs when your carrier’s jump cooldown ends and it is ready to jump again.",
  "ColonisationConstructionDepot": "Occurs when you arrive at a colonisation construction depot.",
  "FetchRemoteModuleCompleted": "Occurs when your remotely fetched modules have arrived.",
  "ShipyardTransferCompleted": "Occurs when your remotely fetched ships have arrived.",

  // Social
  "QuestEvent": "Occurs when your quest advances.",
  "Idle": "Occurs after a prolonged period of inactivity and may trigger proactive comments. Caution: can lead to endless loops if enabled.",
  "CrewAssign": "Occurs when you change a hired NPC crew member’s role, such as activating or idling them.",
  "CrewFire": "Occurs when you dismiss one of your hired crew members from service.",
  "CrewHire": "Occurs when you hire a new NPC crew member, including their name, rank, cost, and faction.",
  "ChangeCrewRole": "Occurs when you switch your role while in multicrew, such as changing from Gunner to Fighter Con.",
  "CrewMemberJoins": "Occurs when another player joins your ship’s multicrew session.",
  "CrewMemberQuits": "Occurs when a multicrew member leaves your ship.",
  "CrewMemberRoleChange": "Occurs when a multicrew member on your ship changes their role, such as switching to Gunner.",
  "EndCrewSession": "Occurs when a multicrew session ends, especially if it is due to a crime.",
  "JoinACrew": "Occurs when you join another commander’s ship via multicrew.",
  "KickCrewMember": "Occurs when you remove a multicrew member from your ship, including automatic removals for crimes.",
  "QuitACrew": "Occurs when you leave another commander’s multicrew session.",
  "NpcCrewRank": "Occurs when one of your hired fighter pilots gains a new combat rank.",
  "Promotion": "Occurs when you gain a new rank in Combat, Trade, Exploration, CQC, or a Navy rank.",
  "Friends": "Occurs when your friend status changes, such as someone coming online or accepting your request.",
  "WingAdd": "Occurs when another commander joins your wing.",
  "WingInvite": "Occurs when you receive a wing invite from another commander.",
  "WingJoin": "Occurs when you join a wing after accepting an invite.",
  "WingLeave": "Occurs when you leave or are removed from a wing.",
  "SendText": "Occurs when you send a text message to another commander or a chat channel.",
  "ReceiveText": "Occurs when you receive a text message from a player or NPC via chat.",
  "AppliedToSquadron": "Occurs when you apply to join a player squadron.",
  "DisbandedSquadron": "Occurs when a squadron you were part of is disbanded.",
  "InvitedToSquadron": "Occurs when you receive a squadron invite.",
  "JoinedSquadron": "Occurs when you successfully join a squadron.",
  "KickedFromSquadron": "Occurs when you are removed from a squadron by its leadership.",
  "LeftSquadron": "Occurs when you leave a squadron voluntarily.",
  "SharedBookmarkToSquadron": "Occurs when you share a galaxy map bookmark with your squadron.",
  "SquadronCreated": "Occurs when you create a new squadron.",
  "SquadronDemotion": "Occurs when you are demoted to a lower rank.",
  "SquadronPromotion": "Occurs when you are promoted to a higher rank.",
  "WonATrophyForSquadron": "Occurs when your squadron earns a trophy for a seasonal or competitive event.",

  // Powerplay
  "PowerplayCollect": "Occurs when you collect Powerplay commodities for your pledged power.",
  "PowerplayDefect": "Occurs when you defect from your current Powerplay power to a new one.",
  "PowerplayDeliver": "Occurs when you deliver Powerplay commodities to a target system.",
  "PowerplayFastTrack": "Occurs when you spend credits to fast-track Powerplay merits.",
  "PowerplayJoin": "Occurs when you pledge allegiance to a Powerplay power.",
  "PowerplayLeave": "Occurs when you leave your current Powerplay power.",
  "PowerplaySalary": "Occurs when you receive a Powerplay salary payout based on your weekly merit rank.",
  "PowerplayVote": "Occurs when you vote for a Powerplay system expansion or control action.",
  "PowerplayVoucher": "Occurs when you redeem combat merits for Powerplay merit points.",


  // Exploration
  "CodexEntry": "Occurs when you make a discovery that gets added to your Codex, including category, region, and discovery information.",
  "DiscoveryScan": "Occurs when you use the Discovery Scanner to detect celestial bodies in a system.",
  "Scan": "Occurs when you perform a detailed scan of a star, planet, or beacon, including data such as body type and atmosphere.",
  "FSSAllBodiesFound": "Occurs when you have discovered every stellar body in a system using the FSS.",
  "FSSBodySignals": "Occurs when you identify signals on a planet or moon using the FSS.",
  "FSSBiologicalSignals": "Occurs when you find a biological signal using the FSS.",
  "FSSDiscoveryScan": "Occurs when you perform a full system scan using the FSS scanner.",
  "FirstPlayerSystemDiscovered":"Occurs if you are the first player to discover a new system.",
  "FleetCarrierDiscovered": "Occurs when you discover a Fleet Carrier signal via the FSS.",
  "ResourceExtractionDiscovered": "Occurs when you discover a Resource Extraction Site signal via the FSS.",
  "InstallationDiscovered": "Occurs when you discover an Installation signal via the FSS.",
  "NavBeaconDiscovered": "Occurs when you discover a Nav Beacon signal via the FSS.",
  "TouristBeaconDiscovered": "Occurs when you discover a Tourist Beacon signal via the FSS.",
  "MegashipDiscovered": "Occurs when you discover a Megaship signal via the FSS.",
  "GenericDiscovered": "Occurs when you discover a generic signal via the FSS.",
  "OutpostDiscovered": "Occurs when you discover an Outpost signal via the FSS.",
  "CombatDiscovered": "Occurs when you discover a Combat signal via the FSS.",
  "StationDiscovered": "Occurs when you discover a Station signal via the FSS.",
  "UnknownSignalDiscovered": "Occurs when you discover an Unknown signal via the FSS.",
  "MaterialCollected": "Occurs when you collect a material, either with your ship or SRV.",
  "MaterialDiscarded": "Occurs when you discard a material from your inventory.",
  "MaterialDiscovered": "Occurs when you discover a material for the first time.",
  "MultiSellExplorationData": "Occurs when you sell multiple exploration data entries in one transaction.",
  "NavBeaconScan": "Occurs when you scan a Nav Beacon and receive system exploration data.",
  "BuyExplorationData": "Occurs when you buy system exploration data from the galaxy map.",
  "SAAScanComplete": "Occurs when you complete surface mapping using the SAA scanner.",
  "SAASignalsFound": "Occurs when your surface scanner detects signals on a planet or ring.",
  "ScanBaryCentre": "Occurs when you scan a barycenter shared by binary orbiting bodies.",
  "SellExplorationData": "Occurs when you sell exploration data to Universal Cartographics.",
  "Screenshot": "Occurs when you take a screenshot, including your location and image details.",
  "ApproachBody": "Occurs when you approach a celestial body and enter orbital cruise.",
  "LeaveBody": "Occurs when you leave a planet’s vicinity and return to full supercruise.",
  "Liftoff": "Occurs when your ship or SRV lifts off from a planetary surface.",
  "Touchdown": "Occurs when your ship lands on a planetary surface.",
  "DatalinkScan": "Occurs when you scan a data link from objects such as satellites or beacons.",
  "DatalinkVoucher": "Occurs when a data link scan yields a credit voucher.",
  "DataScanned": "Occurs when you scan data points such as listening posts or signal relays.",
  "Scanned": "Occurs when your ship is fully scanned by another ship or faction.",
  "USSDrop": "Occurs when you drop into a USS, including its type and threat level.",
  "NoScoopableStars": "Occurs when no scoopable stars are within your jump range.",
  "HGECandidateFound": "Occurs when an FSD jump lands in a High Grade Emissions candidate system, including the likely high-grade materials that can spawn there.",
  "HighValueLandmarksBody": "Occurs when an FSD jump lands in a system with high-value landmarks.",


};
