export const GameEventTooltips: Record<string, string> = {
  // System
  "Cargo": "COVAS:NEXT will react when you start the game by reporting your ship’s cargo inventory, including all onboard commodities and their quantities.",
  "ClearSavedGame": "COVAS:NEXT will react when you reset your Commander save, marking a complete loss of all previous progress.",
  "LoadGame": "COVAS:NEXT will react when you load into the simulation from the main menu, acknowledging your name, ship, credits, location, and game mode.",
  "Shutdown": "COVAS:NEXT will react when you exit the simulation cleanly, marking the end of that session’s log.",
  "NewCommander": "COVAS:NEXT will react when a new Commander is created, documenting the chosen name and starting loadout.",
  "Materials": "COVAS:NEXT will react at startup by listing your current inventory of raw, manufactured, and encoded materials.",
  "Missions": "COVAS:NEXT will react at startup by summarizing your active, failed, and completed missions.",
  "Progress": "COVAS:NEXT will react at startup by providing your current progress toward the next rank in Combat, Trade, Exploration, and more.",
  "Powerplay": "COVAS:NEXT will react at startup when you are pledged to a power, reporting your rank, merits, and allegiance.",
  "Rank": "COVAS:NEXT will react at startup by acknowledging your current ranks in combat, trade, exploration, and both navy affiliations.",
  "Reputation": "COVAS:NEXT will react at startup by reporting your reputation with major factions, from hostile to allied.",
  "Statistics": "COVAS:NEXT will react at startup by compiling your overall commander statistics, including exploration, trading, combat, and on-foot data.",
  "SquadronStartup": "COVAS:NEXT will react at startup by confirming your squadron affiliation and current rank within it.",
  "EngineerProgress": "COVAS:NEXT will react when your status with an Engineer changes, or at startup by reviewing your unlocks and reputation with known Engineers.",

  // Combat
  "Died": "COVAS:NEXT will react when your ship is destroyed and you are killed, identifying the attacker if known.",
  "Resurrect": "COVAS:NEXT will react when you respawn after death, noting your chosen rebuy option, cost, and any financial penalties.",
  "InDanger": "COVAS:NEXT will react when your ship is considered to be in danger.",
  "OutofDanger": "COVAS:NEXT will react when your ship is no longer considered in danger.",
  "CombatEntered": "COVAS:NEXT will react when combat begins.",
  "CombatExited": "COVAS:NEXT will react when combat ends.",
  "LegalStateChanged": "COVAS:NEXT will react when your legal status changes.",
  "CommitCrime": "COVAS:NEXT will react when you commit a crime, recording the faction pressing charges and any resulting fine or bounty.",
  "Bounty": "COVAS:NEXT will react when you receive bounty payments, listing the factions involved and credit values received.",
  "CapShipBond": "COVAS:NEXT will react when you earn a combat bond for helping defeat a capital ship, including details on factions and rewards.",
  "Interdiction": "COVAS:NEXT will react when you attempt to interdict a target in supercruise, noting the result and target details.",
  "Interdicted": "COVAS:NEXT will react when you are interdicted by another ship, including the source and outcome of the attempt.",
  "BeingInterdicted": "COVAS:NEXT will react when your ship is undergoing an interdiction attempt.",
  "EscapeInterdiction": "COVAS:NEXT will react when you successfully evade an interdiction.",
  "FactionKillBond": "COVAS:NEXT will react when you earn a combat bond for assisting in a faction conflict.",
  "FighterDestroyed": "COVAS:NEXT will react when one of your deployed fighters is destroyed.",
  "HeatDamage": "COVAS:NEXT will react when your ship sustains damage from overheating.",
  "HeatWarning": "COVAS:NEXT will react when your ship’s heat levels exceed safe limits.",
  "HullDamage": "COVAS:NEXT will react when your hull integrity drops significantly due to damage.",
  "PVPKill": "COVAS:NEXT will react when you destroy another player’s ship in combat, giving you the victim's name and rank.",
  "ShieldState": "COVAS:NEXT will react when your shields either drop or come back online.",
  "ShipTargetted": "COVAS:NEXT will react when you target another ship, assessing its characteristics.",
  "UnderAttack": "COVAS:NEXT will react when your ship comes under fire.",
  "CockpitBreached": "COVAS:NEXT will react when your ship’s canopy is breached, activating emergency life support.",
  "CrimeVictim": "COVAS:NEXT will react when another player commits a crime against you, identifying the offender and consequences.",
  "SystemsShutdown": "COVAS:NEXT will react when your ship’s systems experience a complete power loss, often due to external interference.",
  "SelfDestruct": "COVAS:NEXT will react when you initiate and complete a self-destruct sequence, confirming your voluntary destruction.",


  // Trading
  "BuyTradeData": "COVAS:NEXT will react when you purchase trade data for another star system. Telling you about the target system and the credit cost of the data.",
  "CollectCargo": "COVAS:NEXT will react when you pick up cargo into your ship’s hold. Telling you about the commodity type, quantity collected, and whether the cargo is considered stolen.",
  "EjectCargo": "COVAS:NEXT will react when you jettison cargo from your ship. Telling you about the item, quantity, abandonment status, and any mission or Powerplay origin.",
  "MarketBuy": "COVAS:NEXT will react when you purchase commodities from a station market. Telling you about the item, quantity, price per unit, and total cost.",
  "MarketSell": "COVAS:NEXT will react when you sell commodities at a station market. It details the commodity sold, quantity, sale price, total profit, and whether it was illicit.",
  "CargoTransfer": "COVAS:NEXT will react when you transfer cargo between your ship and another storage location. Telling you about the items transferred, their quantities, and the direction of movement.",
  "Market": "COVAS:NEXT will react when you access the commodities market interface. Telling you about station and system info and updates the current market prices, supply, and demand.",

  // Mining
  "AsteroidCracked": "COVAS:NEXT will react when you successfully crack open a deep-core asteroid. It indicates the asteroid is now ready for fragment collection.",
  "MiningRefined": "COVAS:NEXT will react when your refinery converts fragments into a full unit of material. Telling you about the completion of refining a metal or mineral.",
  "ProspectedAsteroid": "COVAS:NEXT will react when you scan an asteroid with a prospector limpet. Telling you about the asteroid’s contents, material percentages, and remaining yield.",
  "LaunchDrone": "COVAS:NEXT will react when you launch a limpet drone from your ship. Telling you about the limpet type being deployed.",
  "RememberLimpets": "COVAS:NEXT will react when you have a limpet controller equipped and still have room to purchase limpets.",


  // Ship Updates
  "FSDJump": "COVAS:NEXT will react when you complete a hyperspace jump to a new star system. Telling you about the destination system and key details such as allegiance and security.",
  "FSDTarget": "COVAS:NEXT will react when you select a hyperspace destination. It records the name and summary of the targeted system.",
  "StartJump": "COVAS:NEXT will react when your Frame Shift Drive initiates a jump sequence (just before the countdown). Telling you about whether the jump is interstellar or intra-system.",
  "FsdCharging": "COVAS:NEXT will react when the FSD begins charging for a jump to another system or into supercruise.",
  "SupercruiseEntry": "COVAS:NEXT will react when your ship enters supercruise mode for high-speed travel within a system.",
  "SupercruiseExit": "COVAS:NEXT will react when you drop out of supercruise. Telling you about the type of location you've arrived at.",
  "ApproachSettlement": "COVAS:NEXT will react when you approach a planetary settlement. Telling you about proximity to surface installations.",
  "GlideModeExited": "COVAS:NEXT will react when your ship exits glide mode near a planet’s surface.",
  "GlideModeEntered": "COVAS:NEXT will react when your ship enters a planet’s atmosphere after supercruise.",
  "Docked": "COVAS:NEXT will react when your ship docks successfully at a station or planetary base.",
  "Undocked": "COVAS:NEXT will react when your ship undocks and transitions to free flight.",
  "DockingCanceled": "COVAS:NEXT will react when your docking sequence is cancelled.",
  "DockingDenied": "COVAS:NEXT will react when docking is denied. It includes the reason for denial.",
  "DockingGranted": "COVAS:NEXT will react when a station grants docking permission, including the assigned pad.",
  "DockingRequested": "COVAS:NEXT will react when you request docking clearance at a station.",
  "DockingTimeout": "COVAS:NEXT will react when docking clearance expires due to timeout.",
  "DockingComputerDocking": "COVAS:NEXT will react when the advanced docking computer begins automated docking.",
  "DockingComputerUndocking": "COVAS:NEXT will react when the advanced docking computer initiates undocking procedures.",
  "DockingComputerDeactivated": "COVAS:NEXT will react when the advanced docking computer is deactivated.",
  "NavRoute": "COVAS:NEXT will react when you plot a route across multiple systems on the galaxy map.",
  "NavRouteClear": "COVAS:NEXT will react when your plotted route is cleared from the galaxy map.",
  "CrewLaunchFighter": "COVAS:NEXT will react when a multicrew member launches a fighter from your ship.",
  "VehicleSwitch": "COVAS:NEXT will react when you switch control between your ship and a fighter.",
  "LaunchFighter": "COVAS:NEXT will react when a fighter is deployed from your ship’s hangar.",
  "DockFighter": "COVAS:NEXT will react when a fighter redocks with your ship after deployment.",
  "FighterRebuilt": "COVAS:NEXT will react when a destroyed fighter is rebuilt and becomes available again.",
  "FuelScoop": "COVAS:NEXT will react as you scoop fuel from a star. Telling you about collected quantity and current levels.",
  "RebootRepair": "COVAS:NEXT will react when a reboot/repair sequence is initiated. Telling you about affected modules.",
  "RepairDrone": "COVAS:NEXT will react when your ship is repaired by a maintenance limpet drone.",
  "AfmuRepairs": "COVAS:NEXT will react when you use the AFMU to repair a module. Telling you about repair results and module status.",
  "ModuleInfo": "COVAS:NEXT will react when your ship’s module data is updated. It reflects your current module setup.",
  "Synthesis": "COVAS:NEXT will react when you perform a synthesis. Telling you about the recipe used and materials consumed.",
  "JetConeBoost": "COVAS:NEXT will react when you supercharge your FSD by passing through a neutron or white dwarf jet.",
  "JetConeDamage": "COVAS:NEXT will react when your ship takes damage from a neutron or white dwarf jet cone.",
  "LandingGearUp": "COVAS:NEXT will react when your landing gear is retracted.",
  "LandingGearDown": "COVAS:NEXT will react when your landing gear is deployed.",
  "FlightAssistOn": "COVAS:NEXT will react when flight assist is activated.",
  "FlightAssistOff": "COVAS:NEXT will react when flight assist is deactivated.",
  "HardpointsRetracted": "COVAS:NEXT will react when your ship’s hardpoints are retracted.",
  "HardpointsDeployed": "COVAS:NEXT will react when your ship’s hardpoints are deployed.",
  "LightsOff": "COVAS:NEXT will react when your ship’s lights are switched off.",
  "LightsOn": "COVAS:NEXT will react when your ship’s lights are switched on.",
  "CargoScoopRetracted": "COVAS:NEXT will react when the cargo scoop is retracted.",
  "CargoScoopDeployed": "COVAS:NEXT will react when the cargo scoop is deployed.",
  "SilentRunningOff": "COVAS:NEXT will react when silent running is deactivated.",
  "SilentRunningOn": "COVAS:NEXT will react when silent running is activated.",
  "FuelScoopStarted": "COVAS:NEXT will react when fuel scooping begins.",
  "FuelScoopEnded": "COVAS:NEXT will react when fuel scooping ends.",
  "FsdMassLockEscaped": "COVAS:NEXT will react when you escape mass lock.",
  "FsdMassLocked": "COVAS:NEXT will react when your ship becomes mass locked.",
  "LowFuelWarningCleared": "COVAS:NEXT will react when a low fuel warning is cleared.",
  "LowFuelWarning": "COVAS:NEXT will react when your fuel level is critically low.",
  "NoScoopableStars": "COVAS:NEXT will react when no scoopable stars are within your jump range.",
  "NightVisionOff": "COVAS:NEXT will react when night vision is turned off.",
  "NightVisionOn": "COVAS:NEXT will react when night vision is activated.",
  "SupercruiseDestinationDrop": "COVAS:NEXT will react when you drop out of supercruise at a targeted destination, logging threat level and type.",

  // SRV Updates
  "LaunchSRV": "COVAS:NEXT will react when you deploy an SRV onto a planet's surface. Telling you about the SRV type and loadout being launched.",
  "DockSRV": "COVAS:NEXT will react when your SRV is recovered aboard your ship. Telling you about that the SRV has docked successfully.",
  "SRVDestroyed": "COVAS:NEXT will react when your SRV is destroyed. Telling you about the type and ID of the lost vehicle.",
  "SrvHandbrakeOff": "COVAS:NEXT will react when you disengage the SRV handbrake.",
  "SrvHandbrakeOn": "COVAS:NEXT will react when you engage the SRV handbrake.",
  "SrvTurretViewConnected": "COVAS:NEXT will react when you activate turret view in your SRV.",
  "SrvTurretViewDisconnected": "COVAS:NEXT will react when you exit turret view in your SRV.",
  "SrvDriveAssistOff": "COVAS:NEXT will react when SRV drive assist is turned off.",
  "SrvDriveAssistOn": "COVAS:NEXT will react when SRV drive assist is turned on.",

  // On-Foot Updates
  "Disembark": "COVAS:NEXT will react when you disembark from a ship or SRV to begin on-foot activity.",
  "Embark": "COVAS:NEXT will react when you board a ship or SRV from on-foot, logging the transition and the vehicle details.",
  "BookDropship": "COVAS:NEXT will react when you book a dropship transport to a combat zone via Frontline Solutions.",
  "BookTaxi": "COVAS:NEXT will react when you book an Apex interstellar taxi. Telling you about your destination and ride details.",
  "CancelDropship": "COVAS:NEXT will react when you cancel a booked dropship transport to a combat zone.",
  "CancelTaxi": "COVAS:NEXT will react when you cancel an Apex taxi booking and receive a refund.",
  "CollectItems": "COVAS:NEXT will react when you collect items on foot. Telling you about item details, ownership, and legal status.",
  "DropItems": "COVAS:NEXT will react when you drop items from your backpack onto the ground.",
  "BackpackChange": "COVAS:NEXT will react when your backpack inventory changes. Telling you about what items were added or removed.",
  "BuyMicroResources": "COVAS:NEXT will react when you buy micro-resources from a vendor. Telling you about what you bought and the price.",
  "SellMicroResources": "COVAS:NEXT will react when you sell micro-resources to a vendor. Telling you about what was sold and the credits received.",
  "TransferMicroResources": "COVAS:NEXT will react when you transfer items between your backpack and ship locker. Telling you about items, direction, and quantity.",
  "TradeMicroResources": "COVAS:NEXT will react when you trade items at a bartender. Telling you about what was exchanged and received.",
  "BuySuit": "COVAS:NEXT will react when you purchase a new suit. Telling you about the suit type, ID, and purchase price.",
  "BuyWeapon": "COVAS:NEXT will react when you purchase an on-foot weapon. Telling you about the weapon, class, and cost.",
  "SellWeapon": "COVAS:NEXT will react when you sell an on-foot weapon. Telling you about the weapon and sale price.",
  "UpgradeSuit": "COVAS:NEXT will react when you upgrade a suit to a higher class. Telling you about the new grade, cost, and materials used.",
  "UpgradeWeapon": "COVAS:NEXT will react when you upgrade an on-foot weapon. Telling you about the weapon, new grade, cost, and materials used.",
  "CreateSuitLoadout": "COVAS:NEXT will react when you create a new suit loadout. Telling you about the suit, name, and modules equipped.",
  "WeaponSelected": "COVAS:NEXT will react when you select an on foot weapon.",
  "DeleteSuitLoadout": "COVAS:NEXT will react when you delete a saved suit loadout.",
  "RenameSuitLoadout": "COVAS:NEXT will react when you rename a suit loadout. Telling you about the new name and associated suit.",
  "SwitchSuitLoadout": "COVAS:NEXT will react when you switch suit loadouts. Telling you about the suit, loadout name, and equipped modules.",
  "UseConsumable": "COVAS:NEXT will react when you use a consumable item. Telling you about the type used and its function.",
  "FCMaterials": "COVAS:NEXT will react when you access a fleet carrier bartender’s inventory. Telling you about the tradeable items available.",
  "ScanOrganic": "COVAS:NEXT will react when you scan an organic lifeform using the Genetic Sampler. Telling you about the taxonomy, phase, and location.",
  "SellOrganicData": "COVAS:NEXT will react when you sell organic data to Vista Genomics. Telling you about the transaction and earned credits.",
  "LowOxygenWarningCleared": "COVAS:NEXT will react when your suit’s low oxygen warning clears.",
  "LowOxygenWarning": "COVAS:NEXT will react when your suit issues a low oxygen warning.",
  "LowHealthWarningCleared": "COVAS:NEXT will react when your low health warning clears.",
  "LowHealthWarning": "COVAS:NEXT will react when your suit detects critically low health.",
  "BreathableAtmosphereExited": "COVAS:NEXT will react when you exit a breathable atmosphere.",
  "BreathableAtmosphereEntered": "COVAS:NEXT will react when you enter a breathable atmosphere.",
  "DropShipDeploy": "COVAS:NEXT will react when you are deployed from a dropship into a conflict zone. Telling you about the location and deployment details.",


  // Rewritten Station Tooltips in Immersive Format

  "MissionAbandoned": "COVAS:NEXT will react when you abandon a mission. Telling you about the mission ID, name, and any resulting fine.",
  "MissionAccepted": "COVAS:NEXT will react when you accept a mission. Telling you about the mission ID, name, issuer faction, objectives, rewards, and expiry.",
  "MissionCompleted": "COVAS:NEXT will react when you complete a mission. Telling you about the mission ID, name, completion rewards, and effects on factions.",
  "MissionFailed": "COVAS:NEXT will react when a mission fails. Telling you about the mission ID, name, and any penalties incurred.",
  "MissionRedirected": "COVAS:NEXT will react when a mission is redirected. Telling you about the updated destination and the mission details.",
  "StationServices": "COVAS:NEXT will react when you access the station services interface.",
  "ShipyardBuy": "COVAS:NEXT will react when you purchase a new ship. Telling you about the ship type, price, and disposition of your previous ship.",
  "ShipyardNew": "COVAS:NEXT will react when your new ship purchase is finalized. Telling you about the ship type and assigned ID.",
  "ShipyardSell": "COVAS:NEXT will react when you sell a stored ship. Telling you about the ship type, sale price, and system where it was sold.",
  "ShipyardTransfer": "COVAS:NEXT will react when you request a ship transfer. Telling you about the ship details, distance, cost, and ETA.",
  "ShipyardSwap": "COVAS:NEXT will react when you swap ships at a station. Telling you about the new and previous ship types and their status.",
  "StoredShips": "COVAS:NEXT will react when you view stored ships. Telling you about their locations, types, values, and storage status.",
  "ModuleBuy": "COVAS:NEXT will react when you buy a module. Telling you about the module, slot, cost, and disposition of any replaced module.",
  "ModuleRetrieve": "COVAS:NEXT will react when you retrieve a stored module. Telling you about the item, target ship, slot, and any swapped components.",
  "ModuleSell": "COVAS:NEXT will react when you sell a module from your ship. Telling you about the item, location, and sale amount.",
  "ModuleSellRemote": "COVAS:NEXT will react when you remotely sell a stored module. Telling you about the module and sale price.",
  "ModuleStore": "COVAS:NEXT will react when you store a ship module. Telling you about the module type, origin slot, and modification status.",
  "ModuleSwap": "COVAS:NEXT will react when you swap module positions. Telling you about the from and to slots for the swapped module.",
  "LoadoutEquipModule": "COVAS:NEXT will react when you add a module to a suit loadout. Telling you about the suit, loadout, slot, and module details.",
  "LoadoutRemoveModule": "COVAS:NEXT will react when you remove a module from a suit loadout. Telling you about the item, slot, and suit info.",
  "Outfitting": "COVAS:NEXT will react when you access station outfitting. Telling you about module availability and basic station data.",
  "BuyAmmo": "COVAS:NEXT will react when you restock ammunition. Telling you about the cost of the resupply.",
  "BuyDrones": "COVAS:NEXT will react when you buy limpets. Telling you about the quantity, type, and total purchase cost.",
  "RefuelAll": "COVAS:NEXT will react when you fully refuel your ship. Telling you about the quantity of fuel purchased and total cost.",
  "RefuelPartial": "COVAS:NEXT will react when you partially refuel. Telling you about the fuel added and price paid.",
  "Repair": "COVAS:NEXT will react when you repair ship components. Telling you about the items repaired and repair cost.",
  "RepairAll": "COVAS:NEXT will react when you fully repair your ship. Telling you about the total credits spent for full restoration.",
  "RestockVehicle": "COVAS:NEXT will react when you restock SRVs or fighters. Telling you about the vehicle type, quantity, and purchase price.",
  "FetchRemoteModule": "COVAS:NEXT will react when you request a remote module transfer. Telling you about the module, cost, and source station.",
  "MassModuleStore": "COVAS:NEXT will react when you bulk store modules. Telling you about all modules moved into storage.",
  "ClearImpound": "COVAS:NEXT will react when you clear an impound. Telling you about the ship released and fee paid.",
  "CargoDepot": "COVAS:NEXT will react when you deliver or collect cargo for a wing mission. Telling you about progress and mission status.",
  "CommunityGoal": "COVAS:NEXT will react when community goal data updates. Telling you about progress, tiers, and your contribution.",
  "CommunityGoalDiscard": "COVAS:NEXT will react when you abandon a community goal. Telling you about the goal ID and name.",
  "CommunityGoalJoin": "COVAS:NEXT will react when you join a community goal. Telling you about your enrollment and the goal location.",
  "CommunityGoalReward": "COVAS:NEXT will react when you receive community goal rewards. Telling you about the payout and goal details.",
  "EngineerContribution": "COVAS:NEXT will react when you donate to an engineer. Telling you about the engineer name and the contributions made.",
  "EngineerCraft": "COVAS:NEXT will react when you apply engineering. Telling you about the engineer, blueprint, level, outcome, and materials used.",
  "EngineerLegacyConvert": "COVAS:NEXT will react when you convert a legacy module. Telling you about the module and whether it was a preview.",
  "MaterialTrade": "COVAS:NEXT will react when you trade materials. Telling you about what was exchanged and the trader type.",
  "TechnologyBroker": "COVAS:NEXT will react when you unlock tech at a Tech Broker. Telling you about items unlocked and resources consumed.",
  "PayBounties": "COVAS:NEXT will react when you pay bounty fines. Telling you about the amount paid and factions cleared.",
  "PayFines": "COVAS:NEXT will react when you pay regular fines. Telling you about the fines, broker fees, and faction cleared.",
  "PayLegacyFines": "COVAS:NEXT will react when you clear legacy fines. Telling you about the payment amount and broker fees.",
  "RedeemVoucher": "COVAS:NEXT will react when you redeem a voucher. Telling you about the type, payout, and faction breakdown if applicable.",
  "ScientificResearch": "COVAS:NEXT will react when you contribute to scientific research. Telling you about the items delivered and quantities.",
  "Shipyard": "COVAS:NEXT will react when you access the shipyard. Telling you about available ships and basic station info.",
  "CarrierJump": "COVAS:NEXT will react when your fleet carrier completes a hyperspace jump. Telling you about the destination system.",
  "CarrierBuy": "COVAS:NEXT will react when you purchase a fleet carrier. Telling you about the carrier ID, callsign, and cost.",
  "CarrierStats": "COVAS:NEXT will react when you open carrier management. Telling you about fuel, finances, and services status.",
  "CarrierJumpRequest": "COVAS:NEXT will react when you schedule a carrier jump. Telling you about the destination and departure time.",
  "CarrierDecommission": "COVAS:NEXT will react when you decommission your carrier. Telling you about the refund amount and time of decommission.",
  "CarrierCancelDecommission": "COVAS:NEXT will react when you cancel carrier decommissioning. Telling you about the action and carrier ID.",
  "CarrierBankTransfer": "COVAS:NEXT will react when you transfer funds to or from the carrier bank. Telling you about the direction, amount, and balances.",
  "CarrierDepositFuel": "COVAS:NEXT will react when tritium is added to the carrier. Telling you about the quantity added and current fuel level.",
  "CarrierCrewServices": "COVAS:NEXT will react when carrier services are changed. Telling you about service names and actions taken.",
  "CarrierFinance": "COVAS:NEXT will react when carrier finances are updated. Telling you about the new tax rate and account balances.",
  "CarrierShipPack": "COVAS:NEXT will react when a ship pack is managed on the carrier. Telling you about the pack type, action, and credits spent or refunded.",
  "CarrierModulePack": "COVAS:NEXT will react when a module pack is managed on the carrier. Telling you about the operation and pack details.",
  "CarrierTradeOrder": "COVAS:NEXT will react when you set up a carrier trade order. Telling you about commodity type, order type, quantity, and price.",
  "CarrierDockingPermission": "COVAS:NEXT will react when you change carrier docking permissions. Telling you about the access level and notoriety setting.",
  "CarrierNameChanged": "COVAS:NEXT will react when you rename your carrier. Telling you about the new name and callsign.",
  "CarrierJumpCancelled": "COVAS:NEXT will react when a scheduled carrier jump is cancelled. Telling you about the carrier ID.",
  "ColonisationConstructionDepot": "COVAS:NEXT will react when you arrive at a colonisation construction depot.",

  // Social
  "Idle": "COVAS:NEXT will react when you remain inactive for a prolonged period and proactively make comments.",
  "CrewAssign": "COVAS:NEXT will react when you change a hired NPC crew member’s role — such as activating or idling them.",
  "CrewFire": "COVAS:NEXT will react when you dismiss one of your hired crew members from service.",
  "CrewHire": "COVAS:NEXT will react when you hire a new NPC crew member. It notes their name, rank, cost, and faction.",
  "ChangeCrewRole": "COVAS:NEXT will react when you switch your role while in multicrew, like changing from Gunner to Fighter Con.",
  "CrewMemberJoins": "COVAS:NEXT will react when another player joins your ship’s multicrew session.",
  "CrewMemberQuits": "COVAS:NEXT will react when a multicrew member leaves your ship.",
  "CrewMemberRoleChange": "COVAS:NEXT will react when a multicrew member on your ship changes their role, like switching to Gunner.",
  "EndCrewSession": "COVAS:NEXT will react when a multicrew session ends, especially if it’s due to a crime.",
  "JoinACrew": "COVAS:NEXT will react when you join another commander’s ship via multicrew.",
  "KickCrewMember": "COVAS:NEXT will react when you remove a multicrew member from your ship, including automatic removals for crimes.",
  "QuitACrew": "COVAS:NEXT will react when you leave another commander’s multicrew session.",
  "NpcCrewRank": "COVAS:NEXT will react when one of your hired fighter pilots gains a new combat rank.",
  "Promotion": "COVAS:NEXT will react when you gain a new rank in Combat, Trade, Exploration, CQC, or a Navy rank.",
  "Friends": "COVAS:NEXT will react when your friend status changes — like someone coming online or accepting your request.",
  "WingAdd": "COVAS:NEXT will react when another commander joins your wing.",
  "WingInvite": "COVAS:NEXT will react when you receive a wing invite from another commander.",
  "WingJoin": "COVAS:NEXT will react when you join a wing after accepting an invite.",
  "WingLeave": "COVAS:NEXT will react when you leave or are removed from a wing.",
  "SendText": "COVAS:NEXT will react when you send a text message to another commander or a chat channel.",
  "ReceiveText": "COVAS:NEXT will react when you receive a text message from a player or NPC via chat.",
  "AppliedToSquadron": "COVAS:NEXT will react when you apply to join a player squadron.",
  "DisbandedSquadron": "COVAS:NEXT will react when a squadron you were part of is disbanded.",
  "InvitedToSquadron": "COVAS:NEXT will react when you receive a squadron invite.",
  "JoinedSquadron": "COVAS:NEXT will react when you successfully join a squadron.",
  "KickedFromSquadron": "COVAS:NEXT will react when you’re removed from a squadron by its leadership.",
  "LeftSquadron": "COVAS:NEXT will react when you leave a squadron voluntarily.",
  "SharedBookmarkToSquadron": "COVAS:NEXT will react when you share a galaxy map bookmark with your squadron.",
  "SquadronCreated": "COVAS:NEXT will react when you create a new squadron.",
  "SquadronDemotion": "COVAS:NEXT will react when you are demoted to a lower rank.",
  "SquadronPromotion": "COVAS:NEXT will react when you are promoted to a higher rank.",
  "WonATrophyForSquadron": "COVAS:NEXT will react when your squadron earns a trophy for a seasonal or competitive event.",

  // Powerplay
  "PowerplayCollect": "COVAS:NEXT will react when you collect Powerplay commodities for your pledged power.",
  "PowerplayDefect": "COVAS:NEXT will react when you defect from your current Powerplay power to a new one.",
  "PowerplayDeliver": "COVAS:NEXT will react when you deliver Powerplay commodities to a target system.",
  "PowerplayFastTrack": "COVAS:NEXT will react when you spend credits to fast-track Powerplay merits.",
  "PowerplayJoin": "COVAS:NEXT will react when you pledge allegiance to a Powerplay power.",
  "PowerplayLeave": "COVAS:NEXT will react when you leave your current Powerplay power.",
  "PowerplaySalary": "COVAS:NEXT will react when you receive a Powerplay salary payout based on your weekly merit rank.",
  "PowerplayVote": "COVAS:NEXT will react when you vote for a Powerplay system expansion or control action.",
  "PowerplayVoucher": "COVAS:NEXT will react when you redeem combat merits for Powerplay merit points.",


  // Exploration
  "CodexEntry": "COVAS:NEXT will react when you make a discovery that gets added to your Codex. It includes the category, region, and discovery info.",
  "DiscoveryScan": "COVAS:NEXT will react when you use the Discovery Scanner to detect celestial bodies in a system.",
  "Scan": "COVAS:NEXT will react when you perform a detailed scan of a star, planet, or beacon. It includes data like body type, atmosphere, and more.",
  "FSSAllBodiesFound": "COVAS:NEXT will react when you’ve discovered every stellar body in a system using the FSS.",
  "FSSBodySignals": "COVAS:NEXT will react when you identify signals on a planet or moon using the FSS.",
  "FSSDiscoveryScan": "COVAS:NEXT will react when you perform a full system scan using the FSS scanner.",
  "FSSSignalDiscovered": "COVAS:NEXT will react when you zoom and discover a specific signal source via the FSS.",
  "MaterialCollected": "COVAS:NEXT will react when you collect a material, either with your ship or SRV.",
  "MaterialDiscarded": "COVAS:NEXT will react when you discard a material from your inventory.",
  "MaterialDiscovered": "COVAS:NEXT will react when you discover a material for the first time.",
  "MultiSellExplorationData": "COVAS:NEXT will react when you sell multiple exploration data entries in one transaction.",
  "NavBeaconScan": "COVAS:NEXT will react when you scan a Nav Beacon and receive system exploration data.",
  "BuyExplorationData": "COVAS:NEXT will react when you buy system exploration data from the galaxy map.",
  "SAAScanComplete": "COVAS:NEXT will react when you complete surface mapping using the SAA scanner.",
  "SAASignalsFound": "COVAS:NEXT will react when your surface scanner detects signals on a planet or ring.",
  "ScanBaryCentre": "COVAS:NEXT will react when you scan a barycenter shared by binary orbiting bodies.",
  "SellExplorationData": "COVAS:NEXT will react when you sell exploration data to Universal Cartographics.",
  "Screenshot": "COVAS:NEXT will react when you take a screenshot, logging your location and image details.",
  "ApproachBody": "COVAS:NEXT will react when you approach a celestial body and enter orbital cruise.",
  "LeaveBody": "COVAS:NEXT will react when you leave a planet’s vicinity and return to full supercruise.",
  "Liftoff": "COVAS:NEXT will react when your ship or SRV lifts off from a planetary surface.",
  "Touchdown": "COVAS:NEXT will react when your ship lands on a planetary surface.",
  "DatalinkScan": "COVAS:NEXT will react when you scan a data link from objects like satellites or beacons.",
  "DatalinkVoucher": "COVAS:NEXT will react when a data link scan yields a voucher for credits.",
  "DataScanned": "COVAS:NEXT will react when you scan data points like listening posts or signal relays.",
  "Scanned": "COVAS:NEXT will react when your ship is scanned to completion by another ship or faction.",
  "USSDrop": "COVAS:NEXT will react when you drop into a USS and log its type and threat level."

};